/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as StaffPortalRouteImport } from './routes/staff-portal'
import { Route as RunnerReportsRouteImport } from './routes/runner-reports'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as PayrollReturnRouteImport } from './routes/payroll-return'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DriverPortalRouteImport } from './routes/driver-portal'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as FleetVehicleIdRouteImport } from './routes/fleet.$vehicleId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPortalRoute = StaffPortalRouteImport.update({
  id: '/staff-portal',
  path: '/staff-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerReportsRoute = RunnerReportsRouteImport.update({
  id: '/runner-reports',
  path: '/runner-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollReturnRoute = PayrollReturnRouteImport.update({
  id: '/payroll-return',
  path: '/payroll-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPortalRoute = DriverPortalRouteImport.update({
  id: '/driver-portal',
  path: '/driver-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetVehicleIdRoute = FleetVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => FleetRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/inspections': typeof InspectionsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pnl': typeof PnlRoute
  '/rentals': typeof RentalsRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/staff-portal': typeof StaffPortalRoute
  '/violations': typeof ViolationsRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/sign/$token': typeof SignTokenRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/inspections': typeof InspectionsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pnl': typeof PnlRoute
  '/rentals': typeof RentalsRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/staff-portal': typeof StaffPortalRoute
  '/violations': typeof ViolationsRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/sign/$token': typeof SignTokenRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/inspections': typeof InspectionsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pnl': typeof PnlRoute
  '/rentals': typeof RentalsRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/staff-portal': typeof StaffPortalRoute
  '/violations': typeof ViolationsRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/sign/$token': typeof SignTokenRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/inspections'
    | '/login'
    | '/maintenance'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pnl'
    | '/rentals'
    | '/runner-reports'
    | '/staff-portal'
    | '/violations'
    | '/fleet/$vehicleId'
    | '/sign/$token'
    | '/api/public/hooks/send-reminders'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/inspections'
    | '/login'
    | '/maintenance'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pnl'
    | '/rentals'
    | '/runner-reports'
    | '/staff-portal'
    | '/violations'
    | '/fleet/$vehicleId'
    | '/sign/$token'
    | '/api/public/hooks/send-reminders'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/inspections'
    | '/login'
    | '/maintenance'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pnl'
    | '/rentals'
    | '/runner-reports'
    | '/staff-portal'
    | '/violations'
    | '/fleet/$vehicleId'
    | '/sign/$token'
    | '/api/public/hooks/send-reminders'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DriverPortalRoute: typeof DriverPortalRoute
  DriversRoute: typeof DriversRoute
  ExpensesRoute: typeof ExpensesRoute
  FleetRoute: typeof FleetRouteWithChildren
  InspectionsRoute: typeof InspectionsRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PaymentsRoute: typeof PaymentsRoute
  PayrollRoute: typeof PayrollRoute
  PayrollReturnRoute: typeof PayrollReturnRoute
  PnlRoute: typeof PnlRoute
  RentalsRoute: typeof RentalsRoute
  RunnerReportsRoute: typeof RunnerReportsRoute
  StaffPortalRoute: typeof StaffPortalRoute
  ViolationsRoute: typeof ViolationsRoute
  SignTokenRoute: typeof SignTokenRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-portal': {
      id: '/staff-portal'
      path: '/staff-portal'
      fullPath: '/staff-portal'
      preLoaderRoute: typeof StaffPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner-reports': {
      id: '/runner-reports'
      path: '/runner-reports'
      fullPath: '/runner-reports'
      preLoaderRoute: typeof RunnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-return': {
      id: '/payroll-return'
      path: '/payroll-return'
      fullPath: '/payroll-return'
      preLoaderRoute: typeof PayrollReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-portal': {
      id: '/driver-portal'
      path: '/driver-portal'
      fullPath: '/driver-portal'
      preLoaderRoute: typeof DriverPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$vehicleId': {
      id: '/fleet/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/fleet/$vehicleId'
      preLoaderRoute: typeof FleetVehicleIdRouteImport
      parentRoute: typeof FleetRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FleetRouteChildren {
  FleetVehicleIdRoute: typeof FleetVehicleIdRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetVehicleIdRoute: FleetVehicleIdRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DriverPortalRoute: DriverPortalRoute,
  DriversRoute: DriversRoute,
  ExpensesRoute: ExpensesRoute,
  FleetRoute: FleetRouteWithChildren,
  InspectionsRoute: InspectionsRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PaymentsRoute: PaymentsRoute,
  PayrollRoute: PayrollRoute,
  PayrollReturnRoute: PayrollReturnRoute,
  PnlRoute: PnlRoute,
  RentalsRoute: RentalsRoute,
  RunnerReportsRoute: RunnerReportsRoute,
  StaffPortalRoute: StaffPortalRoute,
  ViolationsRoute: ViolationsRoute,
  SignTokenRoute: SignTokenRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
