/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as SmsLogRouteImport } from './routes/sms-log'
import { Route as SelfAgreementRouteImport } from './routes/self-agreement'
import { Route as RunnerReportsRouteImport } from './routes/runner-reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as RentalAgreementRouteImport } from './routes/rental-agreement'
import { Route as RefundApprovalsRouteImport } from './routes/refund-approvals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as PendingAgreementsRouteImport } from './routes/pending-agreements'
import { Route as PayrollReturnRouteImport } from './routes/payroll-return'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MyRentalsRouteImport } from './routes/my-rentals'
import { Route as MonthlyVehicleReportsRouteImport } from './routes/monthly-vehicle-reports'
import { Route as MigratedReservationsRouteImport } from './routes/migrated-reservations'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JvUnitsRouteImport } from './routes/jv-units'
import { Route as JvPayoutsRouteImport } from './routes/jv-payouts'
import { Route as JvContractsRouteImport } from './routes/jv-contracts'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FleetSnapshotRouteImport } from './routes/fleet-snapshot'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DriverPortalRouteImport } from './routes/driver-portal'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkOrderTokenRouteImport } from './routes/work-order.$token'
import { Route as ViolationsImportsRouteImport } from './routes/violations_.imports'
import { Route as ViolationsImportRouteImport } from './routes/violations_.import'
import { Route as ViolationsExportsRouteImport } from './routes/violations_.exports'
import { Route as ViolationsDisputesRouteImport } from './routes/violations_.disputes'
import { Route as ViolationsBulkUploadRouteImport } from './routes/violations_.bulk-upload'
import { Route as ViolationsAuthoritiesRouteImport } from './routes/violations_.authorities'
import { Route as ViolationTokenRouteImport } from './routes/violation.$token'
import { Route as VerifyPaymentRentalIdRouteImport } from './routes/verify-payment.$rentalId'
import { Route as VerifyCardTokenRouteImport } from './routes/verify-card.$token'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as SignAgreementRetroTokenRouteImport } from './routes/sign-agreement-retro.$token'
import { Route as SetupTokenRouteImport } from './routes/setup.$token'
import { Route as RunnerTaskTokenRouteImport } from './routes/runner-task.$token'
import { Route as RmCardTokenRouteImport } from './routes/rm-card.$token'
import { Route as RentPaidRouteImport } from './routes/rent.paid'
import { Route as RentTokenRouteImport } from './routes/rent.$token'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as PortalSignupRentalIdRouteImport } from './routes/portal-signup.$rentalId'
import { Route as PartQuoteTokenRouteImport } from './routes/part-quote.$token'
import { Route as MyRentalsRentalIdRouteImport } from './routes/my-rentals.$rentalId'
import { Route as MechanicJobTokenRouteImport } from './routes/mechanic-job.$token'
import { Route as FleetVehicleIdRouteImport } from './routes/fleet.$vehicleId'
import { Route as ExtendTokenRouteImport } from './routes/extend.$token'
import { Route as AutoExtendTokenRouteImport } from './routes/auto-extend.$token'
import { Route as AnalyticsUtilizationRouteImport } from './routes/analytics_.utilization'
import { Route as AnalyticsProfitabilityRouteImport } from './routes/analytics_.profitability'
import { Route as AnalyticsPnlDashboardRouteImport } from './routes/analytics_.pnl-dashboard'
import { Route as AnalyticsFailuresRouteImport } from './routes/analytics_.failures'
import { Route as AnalyticsCostsRouteImport } from './routes/analytics_.costs'
import { Route as AnalyticsBreakevenRouteImport } from './routes/analytics_.breakeven'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminPaymentReconciliationRouteImport } from './routes/admin.payment-reconciliation'
import { Route as AdminPartsRouteImport } from './routes/admin.parts'
import { Route as AdminPacketSettingsRouteImport } from './routes/admin.packet-settings'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMechanicsRouteImport } from './routes/admin.mechanics'
import { Route as AdminMalibuPlateReviewRouteImport } from './routes/admin.malibu-plate-review'
import { Route as AdminMaintenanceNotificationsRouteImport } from './routes/admin.maintenance-notifications'
import { Route as AdminImportLegacyRouteImport } from './routes/admin.import-legacy'
import { Route as AdminImportDataRouteImport } from './routes/admin.import-data'
import { Route as AdminExtensionsRouteImport } from './routes/admin.extensions'
import { Route as AdminExpensesRouteImport } from './routes/admin.expenses'
import { Route as AdminExpenseCategoriesRouteImport } from './routes/admin.expense-categories'
import { Route as AdminCreateTaskRouteImport } from './routes/admin.create-task'
import { Route as AdminCategorizeRepairsRouteImport } from './routes/admin.categorize-repairs'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminBackfillPlatesRouteImport } from './routes/admin.backfill-plates'
import { Route as AddCardTokenRouteImport } from './routes/add-card.$token'
import { Route as AccidentReportTokenRouteImport } from './routes/accident-report.$token'
import { Route as WaitlistUploadTokenRouteImport } from './routes/waitlist.upload.$token'
import { Route as RepairDeclineTokenRouteImport } from './routes/repair.decline.$token'
import { Route as RepairAcceptTokenRouteImport } from './routes/repair.accept.$token'
import { Route as RentPortalRentalIdRouteImport } from './routes/rent.portal.$rentalId'
import { Route as InspectVehicleIdTokenRouteImport } from './routes/inspect.$vehicleId.$token'
import { Route as ApiPublicCardholderRefuseRouteImport } from './routes/api/public/cardholder-refuse'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksViolationRemindersRouteImport } from './routes/api/public/hooks/violation-reminders'
import { Route as ApiPublicHooksVerificationRemindersRouteImport } from './routes/api/public/hooks/verification-reminders'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicHooksRepairDigestRouteImport } from './routes/api/public/hooks/repair-digest'
import { Route as ApiPublicHooksMonthlyBackupRouteImport } from './routes/api/public/hooks/monthly-backup'
import { Route as ApiPublicHooksDailyReportsRouteImport } from './routes/api/public/hooks/daily-reports'
import { Route as ApiPublicHooksAutoExtensionLinksRouteImport } from './routes/api/public/hooks/auto-extension-links'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsLogRoute = SmsLogRouteImport.update({
  id: '/sms-log',
  path: '/sms-log',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfAgreementRoute = SelfAgreementRouteImport.update({
  id: '/self-agreement',
  path: '/self-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerReportsRoute = RunnerReportsRouteImport.update({
  id: '/runner-reports',
  path: '/runner-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalAgreementRoute = RentalAgreementRouteImport.update({
  id: '/rental-agreement',
  path: '/rental-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundApprovalsRoute = RefundApprovalsRouteImport.update({
  id: '/refund-approvals',
  path: '/refund-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingAgreementsRoute = PendingAgreementsRouteImport.update({
  id: '/pending-agreements',
  path: '/pending-agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollReturnRoute = PayrollReturnRouteImport.update({
  id: '/payroll-return',
  path: '/payroll-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRentalsRoute = MyRentalsRouteImport.update({
  id: '/my-rentals',
  path: '/my-rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyVehicleReportsRoute = MonthlyVehicleReportsRouteImport.update({
  id: '/monthly-vehicle-reports',
  path: '/monthly-vehicle-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MigratedReservationsRoute = MigratedReservationsRouteImport.update({
  id: '/migrated-reservations',
  path: '/migrated-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JvUnitsRoute = JvUnitsRouteImport.update({
  id: '/jv-units',
  path: '/jv-units',
  getParentRoute: () => rootRouteImport,
} as any)
const JvPayoutsRoute = JvPayoutsRouteImport.update({
  id: '/jv-payouts',
  path: '/jv-payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const JvContractsRoute = JvContractsRouteImport.update({
  id: '/jv-contracts',
  path: '/jv-contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetSnapshotRoute = FleetSnapshotRouteImport.update({
  id: '/fleet-snapshot',
  path: '/fleet-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPortalRoute = DriverPortalRouteImport.update({
  id: '/driver-portal',
  path: '/driver-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrderTokenRoute = WorkOrderTokenRouteImport.update({
  id: '/work-order/$token',
  path: '/work-order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsImportsRoute = ViolationsImportsRouteImport.update({
  id: '/violations_/imports',
  path: '/violations/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsImportRoute = ViolationsImportRouteImport.update({
  id: '/violations_/import',
  path: '/violations/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsExportsRoute = ViolationsExportsRouteImport.update({
  id: '/violations_/exports',
  path: '/violations/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsDisputesRoute = ViolationsDisputesRouteImport.update({
  id: '/violations_/disputes',
  path: '/violations/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsBulkUploadRoute = ViolationsBulkUploadRouteImport.update({
  id: '/violations_/bulk-upload',
  path: '/violations/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsAuthoritiesRoute = ViolationsAuthoritiesRouteImport.update({
  id: '/violations_/authorities',
  path: '/violations/authorities',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationTokenRoute = ViolationTokenRouteImport.update({
  id: '/violation/$token',
  path: '/violation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPaymentRentalIdRoute = VerifyPaymentRentalIdRouteImport.update({
  id: '/verify-payment/$rentalId',
  path: '/verify-payment/$rentalId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCardTokenRoute = VerifyCardTokenRouteImport.update({
  id: '/verify-card/$token',
  path: '/verify-card/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignAgreementRetroTokenRoute = SignAgreementRetroTokenRouteImport.update({
  id: '/sign-agreement-retro/$token',
  path: '/sign-agreement-retro/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTokenRoute = SetupTokenRouteImport.update({
  id: '/setup/$token',
  path: '/setup/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerTaskTokenRoute = RunnerTaskTokenRouteImport.update({
  id: '/runner-task/$token',
  path: '/runner-task/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RmCardTokenRoute = RmCardTokenRouteImport.update({
  id: '/rm-card/$token',
  path: '/rm-card/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RentPaidRoute = RentPaidRouteImport.update({
  id: '/rent/paid',
  path: '/rent/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const RentTokenRoute = RentTokenRouteImport.update({
  id: '/rent/$token',
  path: '/rent/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSignupRentalIdRoute = PortalSignupRentalIdRouteImport.update({
  id: '/portal-signup/$rentalId',
  path: '/portal-signup/$rentalId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartQuoteTokenRoute = PartQuoteTokenRouteImport.update({
  id: '/part-quote/$token',
  path: '/part-quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRentalsRentalIdRoute = MyRentalsRentalIdRouteImport.update({
  id: '/$rentalId',
  path: '/$rentalId',
  getParentRoute: () => MyRentalsRoute,
} as any)
const MechanicJobTokenRoute = MechanicJobTokenRouteImport.update({
  id: '/mechanic-job/$token',
  path: '/mechanic-job/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetVehicleIdRoute = FleetVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => FleetRoute,
} as any)
const ExtendTokenRoute = ExtendTokenRouteImport.update({
  id: '/extend/$token',
  path: '/extend/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoExtendTokenRoute = AutoExtendTokenRouteImport.update({
  id: '/auto-extend/$token',
  path: '/auto-extend/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsUtilizationRoute = AnalyticsUtilizationRouteImport.update({
  id: '/analytics_/utilization',
  path: '/analytics/utilization',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsProfitabilityRoute = AnalyticsProfitabilityRouteImport.update({
  id: '/analytics_/profitability',
  path: '/analytics/profitability',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsPnlDashboardRoute = AnalyticsPnlDashboardRouteImport.update({
  id: '/analytics_/pnl-dashboard',
  path: '/analytics/pnl-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsFailuresRoute = AnalyticsFailuresRouteImport.update({
  id: '/analytics_/failures',
  path: '/analytics/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsCostsRoute = AnalyticsCostsRouteImport.update({
  id: '/analytics_/costs',
  path: '/analytics/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsBreakevenRoute = AnalyticsBreakevenRouteImport.update({
  id: '/analytics_/breakeven',
  path: '/analytics/breakeven',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/admin/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentReconciliationRoute =
  AdminPaymentReconciliationRouteImport.update({
    id: '/admin/payment-reconciliation',
    path: '/admin/payment-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPartsRoute = AdminPartsRouteImport.update({
  id: '/admin/parts',
  path: '/admin/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacketSettingsRoute = AdminPacketSettingsRouteImport.update({
  id: '/admin/packet-settings',
  path: '/admin/packet-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMechanicsRoute = AdminMechanicsRouteImport.update({
  id: '/admin/mechanics',
  path: '/admin/mechanics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMalibuPlateReviewRoute = AdminMalibuPlateReviewRouteImport.update({
  id: '/admin/malibu-plate-review',
  path: '/admin/malibu-plate-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaintenanceNotificationsRoute =
  AdminMaintenanceNotificationsRouteImport.update({
    id: '/admin/maintenance-notifications',
    path: '/admin/maintenance-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminImportLegacyRoute = AdminImportLegacyRouteImport.update({
  id: '/admin/import-legacy',
  path: '/admin/import-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportDataRoute = AdminImportDataRouteImport.update({
  id: '/admin/import-data',
  path: '/admin/import-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExtensionsRoute = AdminExtensionsRouteImport.update({
  id: '/admin/extensions',
  path: '/admin/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/admin/expenses',
  path: '/admin/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpenseCategoriesRoute = AdminExpenseCategoriesRouteImport.update({
  id: '/admin/expense-categories',
  path: '/admin/expense-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateTaskRoute = AdminCreateTaskRouteImport.update({
  id: '/admin/create-task',
  path: '/admin/create-task',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategorizeRepairsRoute = AdminCategorizeRepairsRouteImport.update({
  id: '/admin/categorize-repairs',
  path: '/admin/categorize-repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/admin/backups',
  path: '/admin/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackfillPlatesRoute = AdminBackfillPlatesRouteImport.update({
  id: '/admin/backfill-plates',
  path: '/admin/backfill-plates',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCardTokenRoute = AddCardTokenRouteImport.update({
  id: '/add-card/$token',
  path: '/add-card/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AccidentReportTokenRoute = AccidentReportTokenRouteImport.update({
  id: '/accident-report/$token',
  path: '/accident-report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistUploadTokenRoute = WaitlistUploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => WaitlistRoute,
} as any)
const RepairDeclineTokenRoute = RepairDeclineTokenRouteImport.update({
  id: '/repair/decline/$token',
  path: '/repair/decline/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairAcceptTokenRoute = RepairAcceptTokenRouteImport.update({
  id: '/repair/accept/$token',
  path: '/repair/accept/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RentPortalRentalIdRoute = RentPortalRentalIdRouteImport.update({
  id: '/rent/portal/$rentalId',
  path: '/rent/portal/$rentalId',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectVehicleIdTokenRoute = InspectVehicleIdTokenRouteImport.update({
  id: '/inspect/$vehicleId/$token',
  path: '/inspect/$vehicleId/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCardholderRefuseRoute =
  ApiPublicCardholderRefuseRouteImport.update({
    id: '/api/public/cardholder-refuse',
    path: '/api/public/cardholder-refuse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksViolationRemindersRoute =
  ApiPublicHooksViolationRemindersRouteImport.update({
    id: '/api/public/hooks/violation-reminders',
    path: '/api/public/hooks/violation-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVerificationRemindersRoute =
  ApiPublicHooksVerificationRemindersRouteImport.update({
    id: '/api/public/hooks/verification-reminders',
    path: '/api/public/hooks/verification-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRepairDigestRoute =
  ApiPublicHooksRepairDigestRouteImport.update({
    id: '/api/public/hooks/repair-digest',
    path: '/api/public/hooks/repair-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonthlyBackupRoute =
  ApiPublicHooksMonthlyBackupRouteImport.update({
    id: '/api/public/hooks/monthly-backup',
    path: '/api/public/hooks/monthly-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyReportsRoute =
  ApiPublicHooksDailyReportsRouteImport.update({
    id: '/api/public/hooks/daily-reports',
    path: '/api/public/hooks/daily-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoExtensionLinksRoute =
  ApiPublicHooksAutoExtensionLinksRouteImport.update({
    id: '/api/public/hooks/auto-extension-links',
    path: '/api/public/hooks/auto-extension-links',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/fleet-snapshot': typeof FleetSnapshotRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inspections': typeof InspectionsRoute
  '/insurance': typeof InsuranceRoute
  '/jv-contracts': typeof JvContractsRoute
  '/jv-payouts': typeof JvPayoutsRoute
  '/jv-units': typeof JvUnitsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/migrated-reservations': typeof MigratedReservationsRoute
  '/monthly-vehicle-reports': typeof MonthlyVehicleReportsRoute
  '/my-rentals': typeof MyRentalsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pending-agreements': typeof PendingAgreementsRoute
  '/pnl': typeof PnlRoute
  '/profile': typeof ProfileRoute
  '/refund-approvals': typeof RefundApprovalsRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/rentals': typeof RentalsRoute
  '/repairs': typeof RepairsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/self-agreement': typeof SelfAgreementRoute
  '/sms-log': typeof SmsLogRoute
  '/vendors': typeof VendorsRoute
  '/violations': typeof ViolationsRoute
  '/waitlist': typeof WaitlistRouteWithChildren
  '/accident-report/$token': typeof AccidentReportTokenRoute
  '/add-card/$token': typeof AddCardTokenRoute
  '/admin/backfill-plates': typeof AdminBackfillPlatesRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/categorize-repairs': typeof AdminCategorizeRepairsRoute
  '/admin/create-task': typeof AdminCreateTaskRoute
  '/admin/expense-categories': typeof AdminExpenseCategoriesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/extensions': typeof AdminExtensionsRoute
  '/admin/import-data': typeof AdminImportDataRoute
  '/admin/import-legacy': typeof AdminImportLegacyRoute
  '/admin/maintenance-notifications': typeof AdminMaintenanceNotificationsRoute
  '/admin/malibu-plate-review': typeof AdminMalibuPlateReviewRoute
  '/admin/mechanics': typeof AdminMechanicsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packet-settings': typeof AdminPacketSettingsRoute
  '/admin/parts': typeof AdminPartsRoute
  '/admin/payment-reconciliation': typeof AdminPaymentReconciliationRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/analytics/breakeven': typeof AnalyticsBreakevenRoute
  '/analytics/costs': typeof AnalyticsCostsRoute
  '/analytics/failures': typeof AnalyticsFailuresRoute
  '/analytics/pnl-dashboard': typeof AnalyticsPnlDashboardRoute
  '/analytics/profitability': typeof AnalyticsProfitabilityRoute
  '/analytics/utilization': typeof AnalyticsUtilizationRoute
  '/auto-extend/$token': typeof AutoExtendTokenRoute
  '/extend/$token': typeof ExtendTokenRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/mechanic-job/$token': typeof MechanicJobTokenRoute
  '/my-rentals/$rentalId': typeof MyRentalsRentalIdRoute
  '/part-quote/$token': typeof PartQuoteTokenRoute
  '/portal-signup/$rentalId': typeof PortalSignupRentalIdRoute
  '/portal/$token': typeof PortalTokenRoute
  '/rent/$token': typeof RentTokenRoute
  '/rent/paid': typeof RentPaidRoute
  '/rm-card/$token': typeof RmCardTokenRoute
  '/runner-task/$token': typeof RunnerTaskTokenRoute
  '/setup/$token': typeof SetupTokenRoute
  '/sign-agreement-retro/$token': typeof SignAgreementRetroTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/verify-card/$token': typeof VerifyCardTokenRoute
  '/verify-payment/$rentalId': typeof VerifyPaymentRentalIdRoute
  '/violation/$token': typeof ViolationTokenRoute
  '/violations/authorities': typeof ViolationsAuthoritiesRoute
  '/violations/bulk-upload': typeof ViolationsBulkUploadRoute
  '/violations/disputes': typeof ViolationsDisputesRoute
  '/violations/exports': typeof ViolationsExportsRoute
  '/violations/import': typeof ViolationsImportRoute
  '/violations/imports': typeof ViolationsImportsRoute
  '/work-order/$token': typeof WorkOrderTokenRoute
  '/api/public/cardholder-refuse': typeof ApiPublicCardholderRefuseRoute
  '/inspect/$vehicleId/$token': typeof InspectVehicleIdTokenRoute
  '/rent/portal/$rentalId': typeof RentPortalRentalIdRoute
  '/repair/accept/$token': typeof RepairAcceptTokenRoute
  '/repair/decline/$token': typeof RepairDeclineTokenRoute
  '/waitlist/upload/$token': typeof WaitlistUploadTokenRoute
  '/api/public/hooks/auto-extension-links': typeof ApiPublicHooksAutoExtensionLinksRoute
  '/api/public/hooks/daily-reports': typeof ApiPublicHooksDailyReportsRoute
  '/api/public/hooks/monthly-backup': typeof ApiPublicHooksMonthlyBackupRoute
  '/api/public/hooks/repair-digest': typeof ApiPublicHooksRepairDigestRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/verification-reminders': typeof ApiPublicHooksVerificationRemindersRoute
  '/api/public/hooks/violation-reminders': typeof ApiPublicHooksViolationRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/fleet-snapshot': typeof FleetSnapshotRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inspections': typeof InspectionsRoute
  '/insurance': typeof InsuranceRoute
  '/jv-contracts': typeof JvContractsRoute
  '/jv-payouts': typeof JvPayoutsRoute
  '/jv-units': typeof JvUnitsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/migrated-reservations': typeof MigratedReservationsRoute
  '/monthly-vehicle-reports': typeof MonthlyVehicleReportsRoute
  '/my-rentals': typeof MyRentalsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pending-agreements': typeof PendingAgreementsRoute
  '/pnl': typeof PnlRoute
  '/profile': typeof ProfileRoute
  '/refund-approvals': typeof RefundApprovalsRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/rentals': typeof RentalsRoute
  '/repairs': typeof RepairsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/self-agreement': typeof SelfAgreementRoute
  '/sms-log': typeof SmsLogRoute
  '/vendors': typeof VendorsRoute
  '/violations': typeof ViolationsRoute
  '/waitlist': typeof WaitlistRouteWithChildren
  '/accident-report/$token': typeof AccidentReportTokenRoute
  '/add-card/$token': typeof AddCardTokenRoute
  '/admin/backfill-plates': typeof AdminBackfillPlatesRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/categorize-repairs': typeof AdminCategorizeRepairsRoute
  '/admin/create-task': typeof AdminCreateTaskRoute
  '/admin/expense-categories': typeof AdminExpenseCategoriesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/extensions': typeof AdminExtensionsRoute
  '/admin/import-data': typeof AdminImportDataRoute
  '/admin/import-legacy': typeof AdminImportLegacyRoute
  '/admin/maintenance-notifications': typeof AdminMaintenanceNotificationsRoute
  '/admin/malibu-plate-review': typeof AdminMalibuPlateReviewRoute
  '/admin/mechanics': typeof AdminMechanicsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packet-settings': typeof AdminPacketSettingsRoute
  '/admin/parts': typeof AdminPartsRoute
  '/admin/payment-reconciliation': typeof AdminPaymentReconciliationRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/analytics/breakeven': typeof AnalyticsBreakevenRoute
  '/analytics/costs': typeof AnalyticsCostsRoute
  '/analytics/failures': typeof AnalyticsFailuresRoute
  '/analytics/pnl-dashboard': typeof AnalyticsPnlDashboardRoute
  '/analytics/profitability': typeof AnalyticsProfitabilityRoute
  '/analytics/utilization': typeof AnalyticsUtilizationRoute
  '/auto-extend/$token': typeof AutoExtendTokenRoute
  '/extend/$token': typeof ExtendTokenRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/mechanic-job/$token': typeof MechanicJobTokenRoute
  '/my-rentals/$rentalId': typeof MyRentalsRentalIdRoute
  '/part-quote/$token': typeof PartQuoteTokenRoute
  '/portal-signup/$rentalId': typeof PortalSignupRentalIdRoute
  '/portal/$token': typeof PortalTokenRoute
  '/rent/$token': typeof RentTokenRoute
  '/rent/paid': typeof RentPaidRoute
  '/rm-card/$token': typeof RmCardTokenRoute
  '/runner-task/$token': typeof RunnerTaskTokenRoute
  '/setup/$token': typeof SetupTokenRoute
  '/sign-agreement-retro/$token': typeof SignAgreementRetroTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/verify-card/$token': typeof VerifyCardTokenRoute
  '/verify-payment/$rentalId': typeof VerifyPaymentRentalIdRoute
  '/violation/$token': typeof ViolationTokenRoute
  '/violations/authorities': typeof ViolationsAuthoritiesRoute
  '/violations/bulk-upload': typeof ViolationsBulkUploadRoute
  '/violations/disputes': typeof ViolationsDisputesRoute
  '/violations/exports': typeof ViolationsExportsRoute
  '/violations/import': typeof ViolationsImportRoute
  '/violations/imports': typeof ViolationsImportsRoute
  '/work-order/$token': typeof WorkOrderTokenRoute
  '/api/public/cardholder-refuse': typeof ApiPublicCardholderRefuseRoute
  '/inspect/$vehicleId/$token': typeof InspectVehicleIdTokenRoute
  '/rent/portal/$rentalId': typeof RentPortalRentalIdRoute
  '/repair/accept/$token': typeof RepairAcceptTokenRoute
  '/repair/decline/$token': typeof RepairDeclineTokenRoute
  '/waitlist/upload/$token': typeof WaitlistUploadTokenRoute
  '/api/public/hooks/auto-extension-links': typeof ApiPublicHooksAutoExtensionLinksRoute
  '/api/public/hooks/daily-reports': typeof ApiPublicHooksDailyReportsRoute
  '/api/public/hooks/monthly-backup': typeof ApiPublicHooksMonthlyBackupRoute
  '/api/public/hooks/repair-digest': typeof ApiPublicHooksRepairDigestRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/verification-reminders': typeof ApiPublicHooksVerificationRemindersRoute
  '/api/public/hooks/violation-reminders': typeof ApiPublicHooksViolationRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/fleet-snapshot': typeof FleetSnapshotRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inspections': typeof InspectionsRoute
  '/insurance': typeof InsuranceRoute
  '/jv-contracts': typeof JvContractsRoute
  '/jv-payouts': typeof JvPayoutsRoute
  '/jv-units': typeof JvUnitsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/migrated-reservations': typeof MigratedReservationsRoute
  '/monthly-vehicle-reports': typeof MonthlyVehicleReportsRoute
  '/my-rentals': typeof MyRentalsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pending-agreements': typeof PendingAgreementsRoute
  '/pnl': typeof PnlRoute
  '/profile': typeof ProfileRoute
  '/refund-approvals': typeof RefundApprovalsRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/rentals': typeof RentalsRoute
  '/repairs': typeof RepairsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/self-agreement': typeof SelfAgreementRoute
  '/sms-log': typeof SmsLogRoute
  '/vendors': typeof VendorsRoute
  '/violations': typeof ViolationsRoute
  '/waitlist': typeof WaitlistRouteWithChildren
  '/accident-report/$token': typeof AccidentReportTokenRoute
  '/add-card/$token': typeof AddCardTokenRoute
  '/admin/backfill-plates': typeof AdminBackfillPlatesRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/categorize-repairs': typeof AdminCategorizeRepairsRoute
  '/admin/create-task': typeof AdminCreateTaskRoute
  '/admin/expense-categories': typeof AdminExpenseCategoriesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/extensions': typeof AdminExtensionsRoute
  '/admin/import-data': typeof AdminImportDataRoute
  '/admin/import-legacy': typeof AdminImportLegacyRoute
  '/admin/maintenance-notifications': typeof AdminMaintenanceNotificationsRoute
  '/admin/malibu-plate-review': typeof AdminMalibuPlateReviewRoute
  '/admin/mechanics': typeof AdminMechanicsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packet-settings': typeof AdminPacketSettingsRoute
  '/admin/parts': typeof AdminPartsRoute
  '/admin/payment-reconciliation': typeof AdminPaymentReconciliationRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/analytics_/breakeven': typeof AnalyticsBreakevenRoute
  '/analytics_/costs': typeof AnalyticsCostsRoute
  '/analytics_/failures': typeof AnalyticsFailuresRoute
  '/analytics_/pnl-dashboard': typeof AnalyticsPnlDashboardRoute
  '/analytics_/profitability': typeof AnalyticsProfitabilityRoute
  '/analytics_/utilization': typeof AnalyticsUtilizationRoute
  '/auto-extend/$token': typeof AutoExtendTokenRoute
  '/extend/$token': typeof ExtendTokenRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/mechanic-job/$token': typeof MechanicJobTokenRoute
  '/my-rentals/$rentalId': typeof MyRentalsRentalIdRoute
  '/part-quote/$token': typeof PartQuoteTokenRoute
  '/portal-signup/$rentalId': typeof PortalSignupRentalIdRoute
  '/portal/$token': typeof PortalTokenRoute
  '/rent/$token': typeof RentTokenRoute
  '/rent/paid': typeof RentPaidRoute
  '/rm-card/$token': typeof RmCardTokenRoute
  '/runner-task/$token': typeof RunnerTaskTokenRoute
  '/setup/$token': typeof SetupTokenRoute
  '/sign-agreement-retro/$token': typeof SignAgreementRetroTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/verify-card/$token': typeof VerifyCardTokenRoute
  '/verify-payment/$rentalId': typeof VerifyPaymentRentalIdRoute
  '/violation/$token': typeof ViolationTokenRoute
  '/violations_/authorities': typeof ViolationsAuthoritiesRoute
  '/violations_/bulk-upload': typeof ViolationsBulkUploadRoute
  '/violations_/disputes': typeof ViolationsDisputesRoute
  '/violations_/exports': typeof ViolationsExportsRoute
  '/violations_/import': typeof ViolationsImportRoute
  '/violations_/imports': typeof ViolationsImportsRoute
  '/work-order/$token': typeof WorkOrderTokenRoute
  '/api/public/cardholder-refuse': typeof ApiPublicCardholderRefuseRoute
  '/inspect/$vehicleId/$token': typeof InspectVehicleIdTokenRoute
  '/rent/portal/$rentalId': typeof RentPortalRentalIdRoute
  '/repair/accept/$token': typeof RepairAcceptTokenRoute
  '/repair/decline/$token': typeof RepairDeclineTokenRoute
  '/waitlist/upload/$token': typeof WaitlistUploadTokenRoute
  '/api/public/hooks/auto-extension-links': typeof ApiPublicHooksAutoExtensionLinksRoute
  '/api/public/hooks/daily-reports': typeof ApiPublicHooksDailyReportsRoute
  '/api/public/hooks/monthly-backup': typeof ApiPublicHooksMonthlyBackupRoute
  '/api/public/hooks/repair-digest': typeof ApiPublicHooksRepairDigestRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/verification-reminders': typeof ApiPublicHooksVerificationRemindersRoute
  '/api/public/hooks/violation-reminders': typeof ApiPublicHooksViolationRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/checklist'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/fleet-snapshot'
    | '/forgot-password'
    | '/inspections'
    | '/insurance'
    | '/jv-contracts'
    | '/jv-payouts'
    | '/jv-units'
    | '/login'
    | '/maintenance'
    | '/migrated-reservations'
    | '/monthly-vehicle-reports'
    | '/my-rentals'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pending-agreements'
    | '/pnl'
    | '/profile'
    | '/refund-approvals'
    | '/rental-agreement'
    | '/rentals'
    | '/repairs'
    | '/reset-password'
    | '/runner-reports'
    | '/self-agreement'
    | '/sms-log'
    | '/vendors'
    | '/violations'
    | '/waitlist'
    | '/accident-report/$token'
    | '/add-card/$token'
    | '/admin/backfill-plates'
    | '/admin/backups'
    | '/admin/categorize-repairs'
    | '/admin/create-task'
    | '/admin/expense-categories'
    | '/admin/expenses'
    | '/admin/extensions'
    | '/admin/import-data'
    | '/admin/import-legacy'
    | '/admin/maintenance-notifications'
    | '/admin/malibu-plate-review'
    | '/admin/mechanics'
    | '/admin/notifications'
    | '/admin/packet-settings'
    | '/admin/parts'
    | '/admin/payment-reconciliation'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/waitlist'
    | '/analytics/breakeven'
    | '/analytics/costs'
    | '/analytics/failures'
    | '/analytics/pnl-dashboard'
    | '/analytics/profitability'
    | '/analytics/utilization'
    | '/auto-extend/$token'
    | '/extend/$token'
    | '/fleet/$vehicleId'
    | '/mechanic-job/$token'
    | '/my-rentals/$rentalId'
    | '/part-quote/$token'
    | '/portal-signup/$rentalId'
    | '/portal/$token'
    | '/rent/$token'
    | '/rent/paid'
    | '/rm-card/$token'
    | '/runner-task/$token'
    | '/setup/$token'
    | '/sign-agreement-retro/$token'
    | '/sign/$token'
    | '/verify-card/$token'
    | '/verify-payment/$rentalId'
    | '/violation/$token'
    | '/violations/authorities'
    | '/violations/bulk-upload'
    | '/violations/disputes'
    | '/violations/exports'
    | '/violations/import'
    | '/violations/imports'
    | '/work-order/$token'
    | '/api/public/cardholder-refuse'
    | '/inspect/$vehicleId/$token'
    | '/rent/portal/$rentalId'
    | '/repair/accept/$token'
    | '/repair/decline/$token'
    | '/waitlist/upload/$token'
    | '/api/public/hooks/auto-extension-links'
    | '/api/public/hooks/daily-reports'
    | '/api/public/hooks/monthly-backup'
    | '/api/public/hooks/repair-digest'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/verification-reminders'
    | '/api/public/hooks/violation-reminders'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/checklist'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/fleet-snapshot'
    | '/forgot-password'
    | '/inspections'
    | '/insurance'
    | '/jv-contracts'
    | '/jv-payouts'
    | '/jv-units'
    | '/login'
    | '/maintenance'
    | '/migrated-reservations'
    | '/monthly-vehicle-reports'
    | '/my-rentals'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pending-agreements'
    | '/pnl'
    | '/profile'
    | '/refund-approvals'
    | '/rental-agreement'
    | '/rentals'
    | '/repairs'
    | '/reset-password'
    | '/runner-reports'
    | '/self-agreement'
    | '/sms-log'
    | '/vendors'
    | '/violations'
    | '/waitlist'
    | '/accident-report/$token'
    | '/add-card/$token'
    | '/admin/backfill-plates'
    | '/admin/backups'
    | '/admin/categorize-repairs'
    | '/admin/create-task'
    | '/admin/expense-categories'
    | '/admin/expenses'
    | '/admin/extensions'
    | '/admin/import-data'
    | '/admin/import-legacy'
    | '/admin/maintenance-notifications'
    | '/admin/malibu-plate-review'
    | '/admin/mechanics'
    | '/admin/notifications'
    | '/admin/packet-settings'
    | '/admin/parts'
    | '/admin/payment-reconciliation'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/waitlist'
    | '/analytics/breakeven'
    | '/analytics/costs'
    | '/analytics/failures'
    | '/analytics/pnl-dashboard'
    | '/analytics/profitability'
    | '/analytics/utilization'
    | '/auto-extend/$token'
    | '/extend/$token'
    | '/fleet/$vehicleId'
    | '/mechanic-job/$token'
    | '/my-rentals/$rentalId'
    | '/part-quote/$token'
    | '/portal-signup/$rentalId'
    | '/portal/$token'
    | '/rent/$token'
    | '/rent/paid'
    | '/rm-card/$token'
    | '/runner-task/$token'
    | '/setup/$token'
    | '/sign-agreement-retro/$token'
    | '/sign/$token'
    | '/verify-card/$token'
    | '/verify-payment/$rentalId'
    | '/violation/$token'
    | '/violations/authorities'
    | '/violations/bulk-upload'
    | '/violations/disputes'
    | '/violations/exports'
    | '/violations/import'
    | '/violations/imports'
    | '/work-order/$token'
    | '/api/public/cardholder-refuse'
    | '/inspect/$vehicleId/$token'
    | '/rent/portal/$rentalId'
    | '/repair/accept/$token'
    | '/repair/decline/$token'
    | '/waitlist/upload/$token'
    | '/api/public/hooks/auto-extension-links'
    | '/api/public/hooks/daily-reports'
    | '/api/public/hooks/monthly-backup'
    | '/api/public/hooks/repair-digest'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/verification-reminders'
    | '/api/public/hooks/violation-reminders'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/checklist'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/fleet-snapshot'
    | '/forgot-password'
    | '/inspections'
    | '/insurance'
    | '/jv-contracts'
    | '/jv-payouts'
    | '/jv-units'
    | '/login'
    | '/maintenance'
    | '/migrated-reservations'
    | '/monthly-vehicle-reports'
    | '/my-rentals'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pending-agreements'
    | '/pnl'
    | '/profile'
    | '/refund-approvals'
    | '/rental-agreement'
    | '/rentals'
    | '/repairs'
    | '/reset-password'
    | '/runner-reports'
    | '/self-agreement'
    | '/sms-log'
    | '/vendors'
    | '/violations'
    | '/waitlist'
    | '/accident-report/$token'
    | '/add-card/$token'
    | '/admin/backfill-plates'
    | '/admin/backups'
    | '/admin/categorize-repairs'
    | '/admin/create-task'
    | '/admin/expense-categories'
    | '/admin/expenses'
    | '/admin/extensions'
    | '/admin/import-data'
    | '/admin/import-legacy'
    | '/admin/maintenance-notifications'
    | '/admin/malibu-plate-review'
    | '/admin/mechanics'
    | '/admin/notifications'
    | '/admin/packet-settings'
    | '/admin/parts'
    | '/admin/payment-reconciliation'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/waitlist'
    | '/analytics_/breakeven'
    | '/analytics_/costs'
    | '/analytics_/failures'
    | '/analytics_/pnl-dashboard'
    | '/analytics_/profitability'
    | '/analytics_/utilization'
    | '/auto-extend/$token'
    | '/extend/$token'
    | '/fleet/$vehicleId'
    | '/mechanic-job/$token'
    | '/my-rentals/$rentalId'
    | '/part-quote/$token'
    | '/portal-signup/$rentalId'
    | '/portal/$token'
    | '/rent/$token'
    | '/rent/paid'
    | '/rm-card/$token'
    | '/runner-task/$token'
    | '/setup/$token'
    | '/sign-agreement-retro/$token'
    | '/sign/$token'
    | '/verify-card/$token'
    | '/verify-payment/$rentalId'
    | '/violation/$token'
    | '/violations_/authorities'
    | '/violations_/bulk-upload'
    | '/violations_/disputes'
    | '/violations_/exports'
    | '/violations_/import'
    | '/violations_/imports'
    | '/work-order/$token'
    | '/api/public/cardholder-refuse'
    | '/inspect/$vehicleId/$token'
    | '/rent/portal/$rentalId'
    | '/repair/accept/$token'
    | '/repair/decline/$token'
    | '/waitlist/upload/$token'
    | '/api/public/hooks/auto-extension-links'
    | '/api/public/hooks/daily-reports'
    | '/api/public/hooks/monthly-backup'
    | '/api/public/hooks/repair-digest'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/verification-reminders'
    | '/api/public/hooks/violation-reminders'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  ChecklistRoute: typeof ChecklistRoute
  DriverPortalRoute: typeof DriverPortalRoute
  DriversRoute: typeof DriversRoute
  ExpensesRoute: typeof ExpensesRoute
  FleetRoute: typeof FleetRouteWithChildren
  FleetSnapshotRoute: typeof FleetSnapshotRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InspectionsRoute: typeof InspectionsRoute
  InsuranceRoute: typeof InsuranceRoute
  JvContractsRoute: typeof JvContractsRoute
  JvPayoutsRoute: typeof JvPayoutsRoute
  JvUnitsRoute: typeof JvUnitsRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MigratedReservationsRoute: typeof MigratedReservationsRoute
  MonthlyVehicleReportsRoute: typeof MonthlyVehicleReportsRoute
  MyRentalsRoute: typeof MyRentalsRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  PayrollRoute: typeof PayrollRoute
  PayrollReturnRoute: typeof PayrollReturnRoute
  PendingAgreementsRoute: typeof PendingAgreementsRoute
  PnlRoute: typeof PnlRoute
  ProfileRoute: typeof ProfileRoute
  RefundApprovalsRoute: typeof RefundApprovalsRoute
  RentalAgreementRoute: typeof RentalAgreementRoute
  RentalsRoute: typeof RentalsRoute
  RepairsRoute: typeof RepairsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RunnerReportsRoute: typeof RunnerReportsRoute
  SelfAgreementRoute: typeof SelfAgreementRoute
  SmsLogRoute: typeof SmsLogRoute
  VendorsRoute: typeof VendorsRoute
  ViolationsRoute: typeof ViolationsRoute
  WaitlistRoute: typeof WaitlistRouteWithChildren
  AccidentReportTokenRoute: typeof AccidentReportTokenRoute
  AddCardTokenRoute: typeof AddCardTokenRoute
  AdminBackfillPlatesRoute: typeof AdminBackfillPlatesRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminCategorizeRepairsRoute: typeof AdminCategorizeRepairsRoute
  AdminCreateTaskRoute: typeof AdminCreateTaskRoute
  AdminExpenseCategoriesRoute: typeof AdminExpenseCategoriesRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminExtensionsRoute: typeof AdminExtensionsRoute
  AdminImportDataRoute: typeof AdminImportDataRoute
  AdminImportLegacyRoute: typeof AdminImportLegacyRoute
  AdminMaintenanceNotificationsRoute: typeof AdminMaintenanceNotificationsRoute
  AdminMalibuPlateReviewRoute: typeof AdminMalibuPlateReviewRoute
  AdminMechanicsRoute: typeof AdminMechanicsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPacketSettingsRoute: typeof AdminPacketSettingsRoute
  AdminPartsRoute: typeof AdminPartsRoute
  AdminPaymentReconciliationRoute: typeof AdminPaymentReconciliationRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AnalyticsBreakevenRoute: typeof AnalyticsBreakevenRoute
  AnalyticsCostsRoute: typeof AnalyticsCostsRoute
  AnalyticsFailuresRoute: typeof AnalyticsFailuresRoute
  AnalyticsPnlDashboardRoute: typeof AnalyticsPnlDashboardRoute
  AnalyticsProfitabilityRoute: typeof AnalyticsProfitabilityRoute
  AnalyticsUtilizationRoute: typeof AnalyticsUtilizationRoute
  AutoExtendTokenRoute: typeof AutoExtendTokenRoute
  ExtendTokenRoute: typeof ExtendTokenRoute
  MechanicJobTokenRoute: typeof MechanicJobTokenRoute
  PartQuoteTokenRoute: typeof PartQuoteTokenRoute
  PortalSignupRentalIdRoute: typeof PortalSignupRentalIdRoute
  PortalTokenRoute: typeof PortalTokenRoute
  RentTokenRoute: typeof RentTokenRoute
  RentPaidRoute: typeof RentPaidRoute
  RmCardTokenRoute: typeof RmCardTokenRoute
  RunnerTaskTokenRoute: typeof RunnerTaskTokenRoute
  SetupTokenRoute: typeof SetupTokenRoute
  SignAgreementRetroTokenRoute: typeof SignAgreementRetroTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  VerifyCardTokenRoute: typeof VerifyCardTokenRoute
  VerifyPaymentRentalIdRoute: typeof VerifyPaymentRentalIdRoute
  ViolationTokenRoute: typeof ViolationTokenRoute
  ViolationsAuthoritiesRoute: typeof ViolationsAuthoritiesRoute
  ViolationsBulkUploadRoute: typeof ViolationsBulkUploadRoute
  ViolationsDisputesRoute: typeof ViolationsDisputesRoute
  ViolationsExportsRoute: typeof ViolationsExportsRoute
  ViolationsImportRoute: typeof ViolationsImportRoute
  ViolationsImportsRoute: typeof ViolationsImportsRoute
  WorkOrderTokenRoute: typeof WorkOrderTokenRoute
  ApiPublicCardholderRefuseRoute: typeof ApiPublicCardholderRefuseRoute
  InspectVehicleIdTokenRoute: typeof InspectVehicleIdTokenRoute
  RentPortalRentalIdRoute: typeof RentPortalRentalIdRoute
  RepairAcceptTokenRoute: typeof RepairAcceptTokenRoute
  RepairDeclineTokenRoute: typeof RepairDeclineTokenRoute
  ApiPublicHooksAutoExtensionLinksRoute: typeof ApiPublicHooksAutoExtensionLinksRoute
  ApiPublicHooksDailyReportsRoute: typeof ApiPublicHooksDailyReportsRoute
  ApiPublicHooksMonthlyBackupRoute: typeof ApiPublicHooksMonthlyBackupRoute
  ApiPublicHooksRepairDigestRoute: typeof ApiPublicHooksRepairDigestRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  ApiPublicHooksVerificationRemindersRoute: typeof ApiPublicHooksVerificationRemindersRoute
  ApiPublicHooksViolationRemindersRoute: typeof ApiPublicHooksViolationRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-log': {
      id: '/sms-log'
      path: '/sms-log'
      fullPath: '/sms-log'
      preLoaderRoute: typeof SmsLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-agreement': {
      id: '/self-agreement'
      path: '/self-agreement'
      fullPath: '/self-agreement'
      preLoaderRoute: typeof SelfAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner-reports': {
      id: '/runner-reports'
      path: '/runner-reports'
      fullPath: '/runner-reports'
      preLoaderRoute: typeof RunnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-agreement': {
      id: '/rental-agreement'
      path: '/rental-agreement'
      fullPath: '/rental-agreement'
      preLoaderRoute: typeof RentalAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-approvals': {
      id: '/refund-approvals'
      path: '/refund-approvals'
      fullPath: '/refund-approvals'
      preLoaderRoute: typeof RefundApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-agreements': {
      id: '/pending-agreements'
      path: '/pending-agreements'
      fullPath: '/pending-agreements'
      preLoaderRoute: typeof PendingAgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-return': {
      id: '/payroll-return'
      path: '/payroll-return'
      fullPath: '/payroll-return'
      preLoaderRoute: typeof PayrollReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rentals': {
      id: '/my-rentals'
      path: '/my-rentals'
      fullPath: '/my-rentals'
      preLoaderRoute: typeof MyRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-vehicle-reports': {
      id: '/monthly-vehicle-reports'
      path: '/monthly-vehicle-reports'
      fullPath: '/monthly-vehicle-reports'
      preLoaderRoute: typeof MonthlyVehicleReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrated-reservations': {
      id: '/migrated-reservations'
      path: '/migrated-reservations'
      fullPath: '/migrated-reservations'
      preLoaderRoute: typeof MigratedReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jv-units': {
      id: '/jv-units'
      path: '/jv-units'
      fullPath: '/jv-units'
      preLoaderRoute: typeof JvUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jv-payouts': {
      id: '/jv-payouts'
      path: '/jv-payouts'
      fullPath: '/jv-payouts'
      preLoaderRoute: typeof JvPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jv-contracts': {
      id: '/jv-contracts'
      path: '/jv-contracts'
      fullPath: '/jv-contracts'
      preLoaderRoute: typeof JvContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-snapshot': {
      id: '/fleet-snapshot'
      path: '/fleet-snapshot'
      fullPath: '/fleet-snapshot'
      preLoaderRoute: typeof FleetSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-portal': {
      id: '/driver-portal'
      path: '/driver-portal'
      fullPath: '/driver-portal'
      preLoaderRoute: typeof DriverPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-order/$token': {
      id: '/work-order/$token'
      path: '/work-order/$token'
      fullPath: '/work-order/$token'
      preLoaderRoute: typeof WorkOrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations_/imports': {
      id: '/violations_/imports'
      path: '/violations/imports'
      fullPath: '/violations/imports'
      preLoaderRoute: typeof ViolationsImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations_/import': {
      id: '/violations_/import'
      path: '/violations/import'
      fullPath: '/violations/import'
      preLoaderRoute: typeof ViolationsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations_/exports': {
      id: '/violations_/exports'
      path: '/violations/exports'
      fullPath: '/violations/exports'
      preLoaderRoute: typeof ViolationsExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations_/disputes': {
      id: '/violations_/disputes'
      path: '/violations/disputes'
      fullPath: '/violations/disputes'
      preLoaderRoute: typeof ViolationsDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations_/bulk-upload': {
      id: '/violations_/bulk-upload'
      path: '/violations/bulk-upload'
      fullPath: '/violations/bulk-upload'
      preLoaderRoute: typeof ViolationsBulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations_/authorities': {
      id: '/violations_/authorities'
      path: '/violations/authorities'
      fullPath: '/violations/authorities'
      preLoaderRoute: typeof ViolationsAuthoritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violation/$token': {
      id: '/violation/$token'
      path: '/violation/$token'
      fullPath: '/violation/$token'
      preLoaderRoute: typeof ViolationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-payment/$rentalId': {
      id: '/verify-payment/$rentalId'
      path: '/verify-payment/$rentalId'
      fullPath: '/verify-payment/$rentalId'
      preLoaderRoute: typeof VerifyPaymentRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-card/$token': {
      id: '/verify-card/$token'
      path: '/verify-card/$token'
      fullPath: '/verify-card/$token'
      preLoaderRoute: typeof VerifyCardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-agreement-retro/$token': {
      id: '/sign-agreement-retro/$token'
      path: '/sign-agreement-retro/$token'
      fullPath: '/sign-agreement-retro/$token'
      preLoaderRoute: typeof SignAgreementRetroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$token': {
      id: '/setup/$token'
      path: '/setup/$token'
      fullPath: '/setup/$token'
      preLoaderRoute: typeof SetupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner-task/$token': {
      id: '/runner-task/$token'
      path: '/runner-task/$token'
      fullPath: '/runner-task/$token'
      preLoaderRoute: typeof RunnerTaskTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rm-card/$token': {
      id: '/rm-card/$token'
      path: '/rm-card/$token'
      fullPath: '/rm-card/$token'
      preLoaderRoute: typeof RmCardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/paid': {
      id: '/rent/paid'
      path: '/rent/paid'
      fullPath: '/rent/paid'
      preLoaderRoute: typeof RentPaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$token': {
      id: '/rent/$token'
      path: '/rent/$token'
      fullPath: '/rent/$token'
      preLoaderRoute: typeof RentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-signup/$rentalId': {
      id: '/portal-signup/$rentalId'
      path: '/portal-signup/$rentalId'
      fullPath: '/portal-signup/$rentalId'
      preLoaderRoute: typeof PortalSignupRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-quote/$token': {
      id: '/part-quote/$token'
      path: '/part-quote/$token'
      fullPath: '/part-quote/$token'
      preLoaderRoute: typeof PartQuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rentals/$rentalId': {
      id: '/my-rentals/$rentalId'
      path: '/$rentalId'
      fullPath: '/my-rentals/$rentalId'
      preLoaderRoute: typeof MyRentalsRentalIdRouteImport
      parentRoute: typeof MyRentalsRoute
    }
    '/mechanic-job/$token': {
      id: '/mechanic-job/$token'
      path: '/mechanic-job/$token'
      fullPath: '/mechanic-job/$token'
      preLoaderRoute: typeof MechanicJobTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$vehicleId': {
      id: '/fleet/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/fleet/$vehicleId'
      preLoaderRoute: typeof FleetVehicleIdRouteImport
      parentRoute: typeof FleetRoute
    }
    '/extend/$token': {
      id: '/extend/$token'
      path: '/extend/$token'
      fullPath: '/extend/$token'
      preLoaderRoute: typeof ExtendTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-extend/$token': {
      id: '/auto-extend/$token'
      path: '/auto-extend/$token'
      fullPath: '/auto-extend/$token'
      preLoaderRoute: typeof AutoExtendTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics_/utilization': {
      id: '/analytics_/utilization'
      path: '/analytics/utilization'
      fullPath: '/analytics/utilization'
      preLoaderRoute: typeof AnalyticsUtilizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics_/profitability': {
      id: '/analytics_/profitability'
      path: '/analytics/profitability'
      fullPath: '/analytics/profitability'
      preLoaderRoute: typeof AnalyticsProfitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics_/pnl-dashboard': {
      id: '/analytics_/pnl-dashboard'
      path: '/analytics/pnl-dashboard'
      fullPath: '/analytics/pnl-dashboard'
      preLoaderRoute: typeof AnalyticsPnlDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics_/failures': {
      id: '/analytics_/failures'
      path: '/analytics/failures'
      fullPath: '/analytics/failures'
      preLoaderRoute: typeof AnalyticsFailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics_/costs': {
      id: '/analytics_/costs'
      path: '/analytics/costs'
      fullPath: '/analytics/costs'
      preLoaderRoute: typeof AnalyticsCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics_/breakeven': {
      id: '/analytics_/breakeven'
      path: '/analytics/breakeven'
      fullPath: '/analytics/breakeven'
      preLoaderRoute: typeof AnalyticsBreakevenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-reconciliation': {
      id: '/admin/payment-reconciliation'
      path: '/admin/payment-reconciliation'
      fullPath: '/admin/payment-reconciliation'
      preLoaderRoute: typeof AdminPaymentReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parts': {
      id: '/admin/parts'
      path: '/admin/parts'
      fullPath: '/admin/parts'
      preLoaderRoute: typeof AdminPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packet-settings': {
      id: '/admin/packet-settings'
      path: '/admin/packet-settings'
      fullPath: '/admin/packet-settings'
      preLoaderRoute: typeof AdminPacketSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mechanics': {
      id: '/admin/mechanics'
      path: '/admin/mechanics'
      fullPath: '/admin/mechanics'
      preLoaderRoute: typeof AdminMechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/malibu-plate-review': {
      id: '/admin/malibu-plate-review'
      path: '/admin/malibu-plate-review'
      fullPath: '/admin/malibu-plate-review'
      preLoaderRoute: typeof AdminMalibuPlateReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maintenance-notifications': {
      id: '/admin/maintenance-notifications'
      path: '/admin/maintenance-notifications'
      fullPath: '/admin/maintenance-notifications'
      preLoaderRoute: typeof AdminMaintenanceNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import-legacy': {
      id: '/admin/import-legacy'
      path: '/admin/import-legacy'
      fullPath: '/admin/import-legacy'
      preLoaderRoute: typeof AdminImportLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import-data': {
      id: '/admin/import-data'
      path: '/admin/import-data'
      fullPath: '/admin/import-data'
      preLoaderRoute: typeof AdminImportDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/extensions': {
      id: '/admin/extensions'
      path: '/admin/extensions'
      fullPath: '/admin/extensions'
      preLoaderRoute: typeof AdminExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/expense-categories': {
      id: '/admin/expense-categories'
      path: '/admin/expense-categories'
      fullPath: '/admin/expense-categories'
      preLoaderRoute: typeof AdminExpenseCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-task': {
      id: '/admin/create-task'
      path: '/admin/create-task'
      fullPath: '/admin/create-task'
      preLoaderRoute: typeof AdminCreateTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorize-repairs': {
      id: '/admin/categorize-repairs'
      path: '/admin/categorize-repairs'
      fullPath: '/admin/categorize-repairs'
      preLoaderRoute: typeof AdminCategorizeRepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backfill-plates': {
      id: '/admin/backfill-plates'
      path: '/admin/backfill-plates'
      fullPath: '/admin/backfill-plates'
      preLoaderRoute: typeof AdminBackfillPlatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-card/$token': {
      id: '/add-card/$token'
      path: '/add-card/$token'
      fullPath: '/add-card/$token'
      preLoaderRoute: typeof AddCardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accident-report/$token': {
      id: '/accident-report/$token'
      path: '/accident-report/$token'
      fullPath: '/accident-report/$token'
      preLoaderRoute: typeof AccidentReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/upload/$token': {
      id: '/waitlist/upload/$token'
      path: '/upload/$token'
      fullPath: '/waitlist/upload/$token'
      preLoaderRoute: typeof WaitlistUploadTokenRouteImport
      parentRoute: typeof WaitlistRoute
    }
    '/repair/decline/$token': {
      id: '/repair/decline/$token'
      path: '/repair/decline/$token'
      fullPath: '/repair/decline/$token'
      preLoaderRoute: typeof RepairDeclineTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair/accept/$token': {
      id: '/repair/accept/$token'
      path: '/repair/accept/$token'
      fullPath: '/repair/accept/$token'
      preLoaderRoute: typeof RepairAcceptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/portal/$rentalId': {
      id: '/rent/portal/$rentalId'
      path: '/rent/portal/$rentalId'
      fullPath: '/rent/portal/$rentalId'
      preLoaderRoute: typeof RentPortalRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$vehicleId/$token': {
      id: '/inspect/$vehicleId/$token'
      path: '/inspect/$vehicleId/$token'
      fullPath: '/inspect/$vehicleId/$token'
      preLoaderRoute: typeof InspectVehicleIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cardholder-refuse': {
      id: '/api/public/cardholder-refuse'
      path: '/api/public/cardholder-refuse'
      fullPath: '/api/public/cardholder-refuse'
      preLoaderRoute: typeof ApiPublicCardholderRefuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/violation-reminders': {
      id: '/api/public/hooks/violation-reminders'
      path: '/api/public/hooks/violation-reminders'
      fullPath: '/api/public/hooks/violation-reminders'
      preLoaderRoute: typeof ApiPublicHooksViolationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verification-reminders': {
      id: '/api/public/hooks/verification-reminders'
      path: '/api/public/hooks/verification-reminders'
      fullPath: '/api/public/hooks/verification-reminders'
      preLoaderRoute: typeof ApiPublicHooksVerificationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/repair-digest': {
      id: '/api/public/hooks/repair-digest'
      path: '/api/public/hooks/repair-digest'
      fullPath: '/api/public/hooks/repair-digest'
      preLoaderRoute: typeof ApiPublicHooksRepairDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monthly-backup': {
      id: '/api/public/hooks/monthly-backup'
      path: '/api/public/hooks/monthly-backup'
      fullPath: '/api/public/hooks/monthly-backup'
      preLoaderRoute: typeof ApiPublicHooksMonthlyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-reports': {
      id: '/api/public/hooks/daily-reports'
      path: '/api/public/hooks/daily-reports'
      fullPath: '/api/public/hooks/daily-reports'
      preLoaderRoute: typeof ApiPublicHooksDailyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-extension-links': {
      id: '/api/public/hooks/auto-extension-links'
      path: '/api/public/hooks/auto-extension-links'
      fullPath: '/api/public/hooks/auto-extension-links'
      preLoaderRoute: typeof ApiPublicHooksAutoExtensionLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FleetRouteChildren {
  FleetVehicleIdRoute: typeof FleetVehicleIdRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetVehicleIdRoute: FleetVehicleIdRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

interface MyRentalsRouteChildren {
  MyRentalsRentalIdRoute: typeof MyRentalsRentalIdRoute
}

const MyRentalsRouteChildren: MyRentalsRouteChildren = {
  MyRentalsRentalIdRoute: MyRentalsRentalIdRoute,
}

const MyRentalsRouteWithChildren = MyRentalsRoute._addFileChildren(
  MyRentalsRouteChildren,
)

interface WaitlistRouteChildren {
  WaitlistUploadTokenRoute: typeof WaitlistUploadTokenRoute
}

const WaitlistRouteChildren: WaitlistRouteChildren = {
  WaitlistUploadTokenRoute: WaitlistUploadTokenRoute,
}

const WaitlistRouteWithChildren = WaitlistRoute._addFileChildren(
  WaitlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  ChecklistRoute: ChecklistRoute,
  DriverPortalRoute: DriverPortalRoute,
  DriversRoute: DriversRoute,
  ExpensesRoute: ExpensesRoute,
  FleetRoute: FleetRouteWithChildren,
  FleetSnapshotRoute: FleetSnapshotRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InspectionsRoute: InspectionsRoute,
  InsuranceRoute: InsuranceRoute,
  JvContractsRoute: JvContractsRoute,
  JvPayoutsRoute: JvPayoutsRoute,
  JvUnitsRoute: JvUnitsRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  MigratedReservationsRoute: MigratedReservationsRoute,
  MonthlyVehicleReportsRoute: MonthlyVehicleReportsRoute,
  MyRentalsRoute: MyRentalsRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  PayrollRoute: PayrollRoute,
  PayrollReturnRoute: PayrollReturnRoute,
  PendingAgreementsRoute: PendingAgreementsRoute,
  PnlRoute: PnlRoute,
  ProfileRoute: ProfileRoute,
  RefundApprovalsRoute: RefundApprovalsRoute,
  RentalAgreementRoute: RentalAgreementRoute,
  RentalsRoute: RentalsRoute,
  RepairsRoute: RepairsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RunnerReportsRoute: RunnerReportsRoute,
  SelfAgreementRoute: SelfAgreementRoute,
  SmsLogRoute: SmsLogRoute,
  VendorsRoute: VendorsRoute,
  ViolationsRoute: ViolationsRoute,
  WaitlistRoute: WaitlistRouteWithChildren,
  AccidentReportTokenRoute: AccidentReportTokenRoute,
  AddCardTokenRoute: AddCardTokenRoute,
  AdminBackfillPlatesRoute: AdminBackfillPlatesRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminCategorizeRepairsRoute: AdminCategorizeRepairsRoute,
  AdminCreateTaskRoute: AdminCreateTaskRoute,
  AdminExpenseCategoriesRoute: AdminExpenseCategoriesRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminExtensionsRoute: AdminExtensionsRoute,
  AdminImportDataRoute: AdminImportDataRoute,
  AdminImportLegacyRoute: AdminImportLegacyRoute,
  AdminMaintenanceNotificationsRoute: AdminMaintenanceNotificationsRoute,
  AdminMalibuPlateReviewRoute: AdminMalibuPlateReviewRoute,
  AdminMechanicsRoute: AdminMechanicsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPacketSettingsRoute: AdminPacketSettingsRoute,
  AdminPartsRoute: AdminPartsRoute,
  AdminPaymentReconciliationRoute: AdminPaymentReconciliationRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AnalyticsBreakevenRoute: AnalyticsBreakevenRoute,
  AnalyticsCostsRoute: AnalyticsCostsRoute,
  AnalyticsFailuresRoute: AnalyticsFailuresRoute,
  AnalyticsPnlDashboardRoute: AnalyticsPnlDashboardRoute,
  AnalyticsProfitabilityRoute: AnalyticsProfitabilityRoute,
  AnalyticsUtilizationRoute: AnalyticsUtilizationRoute,
  AutoExtendTokenRoute: AutoExtendTokenRoute,
  ExtendTokenRoute: ExtendTokenRoute,
  MechanicJobTokenRoute: MechanicJobTokenRoute,
  PartQuoteTokenRoute: PartQuoteTokenRoute,
  PortalSignupRentalIdRoute: PortalSignupRentalIdRoute,
  PortalTokenRoute: PortalTokenRoute,
  RentTokenRoute: RentTokenRoute,
  RentPaidRoute: RentPaidRoute,
  RmCardTokenRoute: RmCardTokenRoute,
  RunnerTaskTokenRoute: RunnerTaskTokenRoute,
  SetupTokenRoute: SetupTokenRoute,
  SignAgreementRetroTokenRoute: SignAgreementRetroTokenRoute,
  SignTokenRoute: SignTokenRoute,
  VerifyCardTokenRoute: VerifyCardTokenRoute,
  VerifyPaymentRentalIdRoute: VerifyPaymentRentalIdRoute,
  ViolationTokenRoute: ViolationTokenRoute,
  ViolationsAuthoritiesRoute: ViolationsAuthoritiesRoute,
  ViolationsBulkUploadRoute: ViolationsBulkUploadRoute,
  ViolationsDisputesRoute: ViolationsDisputesRoute,
  ViolationsExportsRoute: ViolationsExportsRoute,
  ViolationsImportRoute: ViolationsImportRoute,
  ViolationsImportsRoute: ViolationsImportsRoute,
  WorkOrderTokenRoute: WorkOrderTokenRoute,
  ApiPublicCardholderRefuseRoute: ApiPublicCardholderRefuseRoute,
  InspectVehicleIdTokenRoute: InspectVehicleIdTokenRoute,
  RentPortalRentalIdRoute: RentPortalRentalIdRoute,
  RepairAcceptTokenRoute: RepairAcceptTokenRoute,
  RepairDeclineTokenRoute: RepairDeclineTokenRoute,
  ApiPublicHooksAutoExtensionLinksRoute: ApiPublicHooksAutoExtensionLinksRoute,
  ApiPublicHooksDailyReportsRoute: ApiPublicHooksDailyReportsRoute,
  ApiPublicHooksMonthlyBackupRoute: ApiPublicHooksMonthlyBackupRoute,
  ApiPublicHooksRepairDigestRoute: ApiPublicHooksRepairDigestRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  ApiPublicHooksVerificationRemindersRoute:
    ApiPublicHooksVerificationRemindersRoute,
  ApiPublicHooksViolationRemindersRoute: ApiPublicHooksViolationRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
