/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as SmsLogRouteImport } from './routes/sms-log'
import { Route as RunnerReportsRouteImport } from './routes/runner-reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as RentalAgreementRouteImport } from './routes/rental-agreement'
import { Route as RefundApprovalsRouteImport } from './routes/refund-approvals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as PendingAgreementsRouteImport } from './routes/pending-agreements'
import { Route as PayrollReturnRouteImport } from './routes/payroll-return'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MyRentalsRouteImport } from './routes/my-rentals'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DriverPortalRouteImport } from './routes/driver-portal'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkOrderTokenRouteImport } from './routes/work-order.$token'
import { Route as ViolationsDisputesRouteImport } from './routes/violations_.disputes'
import { Route as ViolationsBulkUploadRouteImport } from './routes/violations_.bulk-upload'
import { Route as ViolationTokenRouteImport } from './routes/violation.$token'
import { Route as VerifyPaymentRentalIdRouteImport } from './routes/verify-payment.$rentalId'
import { Route as VerifyCardTokenRouteImport } from './routes/verify-card.$token'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as SetupTokenRouteImport } from './routes/setup.$token'
import { Route as RunnerTaskTokenRouteImport } from './routes/runner-task.$token'
import { Route as RmCardTokenRouteImport } from './routes/rm-card.$token'
import { Route as RentPaidRouteImport } from './routes/rent.paid'
import { Route as RentTokenRouteImport } from './routes/rent.$token'
import { Route as PortalSignupRentalIdRouteImport } from './routes/portal-signup.$rentalId'
import { Route as MyRentalsRentalIdRouteImport } from './routes/my-rentals.$rentalId'
import { Route as MechanicJobTokenRouteImport } from './routes/mechanic-job.$token'
import { Route as FleetVehicleIdRouteImport } from './routes/fleet.$vehicleId'
import { Route as ExtendTokenRouteImport } from './routes/extend.$token'
import { Route as AutoExtendTokenRouteImport } from './routes/auto-extend.$token'
import { Route as AnalyticsUtilizationRouteImport } from './routes/analytics.utilization'
import { Route as AnalyticsProfitabilityRouteImport } from './routes/analytics.profitability'
import { Route as AnalyticsFailuresRouteImport } from './routes/analytics.failures'
import { Route as AnalyticsCostsRouteImport } from './routes/analytics.costs'
import { Route as AnalyticsBreakevenRouteImport } from './routes/analytics.breakeven'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminExtensionsRouteImport } from './routes/admin.extensions'
import { Route as AdminCreateTaskRouteImport } from './routes/admin.create-task'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as ViolationTokenAffidavitRouteImport } from './routes/violation.$token_.affidavit'
import { Route as RentPortalRentalIdRouteImport } from './routes/rent.portal.$rentalId'
import { Route as InspectVehicleIdTokenRouteImport } from './routes/inspect.$vehicleId.$token'
import { Route as ApiPublicCardholderRefuseRouteImport } from './routes/api/public/cardholder-refuse'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksViolationRemindersRouteImport } from './routes/api/public/hooks/violation-reminders'
import { Route as ApiPublicHooksVerificationRemindersRouteImport } from './routes/api/public/hooks/verification-reminders'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicHooksRepairDigestRouteImport } from './routes/api/public/hooks/repair-digest'
import { Route as ApiPublicHooksMonthlyBackupRouteImport } from './routes/api/public/hooks/monthly-backup'
import { Route as ApiPublicHooksDailyReportsRouteImport } from './routes/api/public/hooks/daily-reports'
import { Route as ApiPublicHooksAutoExtensionLinksRouteImport } from './routes/api/public/hooks/auto-extension-links'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsLogRoute = SmsLogRouteImport.update({
  id: '/sms-log',
  path: '/sms-log',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerReportsRoute = RunnerReportsRouteImport.update({
  id: '/runner-reports',
  path: '/runner-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalAgreementRoute = RentalAgreementRouteImport.update({
  id: '/rental-agreement',
  path: '/rental-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundApprovalsRoute = RefundApprovalsRouteImport.update({
  id: '/refund-approvals',
  path: '/refund-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingAgreementsRoute = PendingAgreementsRouteImport.update({
  id: '/pending-agreements',
  path: '/pending-agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollReturnRoute = PayrollReturnRouteImport.update({
  id: '/payroll-return',
  path: '/payroll-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRentalsRoute = MyRentalsRouteImport.update({
  id: '/my-rentals',
  path: '/my-rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPortalRoute = DriverPortalRouteImport.update({
  id: '/driver-portal',
  path: '/driver-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrderTokenRoute = WorkOrderTokenRouteImport.update({
  id: '/work-order/$token',
  path: '/work-order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsDisputesRoute = ViolationsDisputesRouteImport.update({
  id: '/violations_/disputes',
  path: '/violations/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsBulkUploadRoute = ViolationsBulkUploadRouteImport.update({
  id: '/violations_/bulk-upload',
  path: '/violations/bulk-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationTokenRoute = ViolationTokenRouteImport.update({
  id: '/violation/$token',
  path: '/violation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPaymentRentalIdRoute = VerifyPaymentRentalIdRouteImport.update({
  id: '/verify-payment/$rentalId',
  path: '/verify-payment/$rentalId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCardTokenRoute = VerifyCardTokenRouteImport.update({
  id: '/verify-card/$token',
  path: '/verify-card/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTokenRoute = SetupTokenRouteImport.update({
  id: '/setup/$token',
  path: '/setup/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerTaskTokenRoute = RunnerTaskTokenRouteImport.update({
  id: '/runner-task/$token',
  path: '/runner-task/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RmCardTokenRoute = RmCardTokenRouteImport.update({
  id: '/rm-card/$token',
  path: '/rm-card/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RentPaidRoute = RentPaidRouteImport.update({
  id: '/rent/paid',
  path: '/rent/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const RentTokenRoute = RentTokenRouteImport.update({
  id: '/rent/$token',
  path: '/rent/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSignupRentalIdRoute = PortalSignupRentalIdRouteImport.update({
  id: '/portal-signup/$rentalId',
  path: '/portal-signup/$rentalId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRentalsRentalIdRoute = MyRentalsRentalIdRouteImport.update({
  id: '/$rentalId',
  path: '/$rentalId',
  getParentRoute: () => MyRentalsRoute,
} as any)
const MechanicJobTokenRoute = MechanicJobTokenRouteImport.update({
  id: '/mechanic-job/$token',
  path: '/mechanic-job/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetVehicleIdRoute = FleetVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => FleetRoute,
} as any)
const ExtendTokenRoute = ExtendTokenRouteImport.update({
  id: '/extend/$token',
  path: '/extend/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoExtendTokenRoute = AutoExtendTokenRouteImport.update({
  id: '/auto-extend/$token',
  path: '/auto-extend/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsUtilizationRoute = AnalyticsUtilizationRouteImport.update({
  id: '/utilization',
  path: '/utilization',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsProfitabilityRoute = AnalyticsProfitabilityRouteImport.update({
  id: '/profitability',
  path: '/profitability',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsFailuresRoute = AnalyticsFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsCostsRoute = AnalyticsCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsBreakevenRoute = AnalyticsBreakevenRouteImport.update({
  id: '/breakeven',
  path: '/breakeven',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExtensionsRoute = AdminExtensionsRouteImport.update({
  id: '/admin/extensions',
  path: '/admin/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateTaskRoute = AdminCreateTaskRouteImport.update({
  id: '/admin/create-task',
  path: '/admin/create-task',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/admin/backups',
  path: '/admin/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationTokenAffidavitRoute = ViolationTokenAffidavitRouteImport.update({
  id: '/violation/$token_/affidavit',
  path: '/violation/$token/affidavit',
  getParentRoute: () => rootRouteImport,
} as any)
const RentPortalRentalIdRoute = RentPortalRentalIdRouteImport.update({
  id: '/rent/portal/$rentalId',
  path: '/rent/portal/$rentalId',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectVehicleIdTokenRoute = InspectVehicleIdTokenRouteImport.update({
  id: '/inspect/$vehicleId/$token',
  path: '/inspect/$vehicleId/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCardholderRefuseRoute =
  ApiPublicCardholderRefuseRouteImport.update({
    id: '/api/public/cardholder-refuse',
    path: '/api/public/cardholder-refuse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksViolationRemindersRoute =
  ApiPublicHooksViolationRemindersRouteImport.update({
    id: '/api/public/hooks/violation-reminders',
    path: '/api/public/hooks/violation-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVerificationRemindersRoute =
  ApiPublicHooksVerificationRemindersRouteImport.update({
    id: '/api/public/hooks/verification-reminders',
    path: '/api/public/hooks/verification-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRepairDigestRoute =
  ApiPublicHooksRepairDigestRouteImport.update({
    id: '/api/public/hooks/repair-digest',
    path: '/api/public/hooks/repair-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonthlyBackupRoute =
  ApiPublicHooksMonthlyBackupRouteImport.update({
    id: '/api/public/hooks/monthly-backup',
    path: '/api/public/hooks/monthly-backup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyReportsRoute =
  ApiPublicHooksDailyReportsRouteImport.update({
    id: '/api/public/hooks/daily-reports',
    path: '/api/public/hooks/daily-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoExtensionLinksRoute =
  ApiPublicHooksAutoExtensionLinksRouteImport.update({
    id: '/api/public/hooks/auto-extension-links',
    path: '/api/public/hooks/auto-extension-links',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inspections': typeof InspectionsRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-rentals': typeof MyRentalsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pending-agreements': typeof PendingAgreementsRoute
  '/pnl': typeof PnlRoute
  '/profile': typeof ProfileRoute
  '/refund-approvals': typeof RefundApprovalsRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/rentals': typeof RentalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/sms-log': typeof SmsLogRoute
  '/vendors': typeof VendorsRoute
  '/violations': typeof ViolationsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/create-task': typeof AdminCreateTaskRoute
  '/admin/extensions': typeof AdminExtensionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/breakeven': typeof AnalyticsBreakevenRoute
  '/analytics/costs': typeof AnalyticsCostsRoute
  '/analytics/failures': typeof AnalyticsFailuresRoute
  '/analytics/profitability': typeof AnalyticsProfitabilityRoute
  '/analytics/utilization': typeof AnalyticsUtilizationRoute
  '/auto-extend/$token': typeof AutoExtendTokenRoute
  '/extend/$token': typeof ExtendTokenRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/mechanic-job/$token': typeof MechanicJobTokenRoute
  '/my-rentals/$rentalId': typeof MyRentalsRentalIdRoute
  '/portal-signup/$rentalId': typeof PortalSignupRentalIdRoute
  '/rent/$token': typeof RentTokenRoute
  '/rent/paid': typeof RentPaidRoute
  '/rm-card/$token': typeof RmCardTokenRoute
  '/runner-task/$token': typeof RunnerTaskTokenRoute
  '/setup/$token': typeof SetupTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/verify-card/$token': typeof VerifyCardTokenRoute
  '/verify-payment/$rentalId': typeof VerifyPaymentRentalIdRoute
  '/violation/$token': typeof ViolationTokenRoute
  '/violations/bulk-upload': typeof ViolationsBulkUploadRoute
  '/violations/disputes': typeof ViolationsDisputesRoute
  '/work-order/$token': typeof WorkOrderTokenRoute
  '/api/public/cardholder-refuse': typeof ApiPublicCardholderRefuseRoute
  '/inspect/$vehicleId/$token': typeof InspectVehicleIdTokenRoute
  '/rent/portal/$rentalId': typeof RentPortalRentalIdRoute
  '/violation/$token/affidavit': typeof ViolationTokenAffidavitRoute
  '/api/public/hooks/auto-extension-links': typeof ApiPublicHooksAutoExtensionLinksRoute
  '/api/public/hooks/daily-reports': typeof ApiPublicHooksDailyReportsRoute
  '/api/public/hooks/monthly-backup': typeof ApiPublicHooksMonthlyBackupRoute
  '/api/public/hooks/repair-digest': typeof ApiPublicHooksRepairDigestRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/verification-reminders': typeof ApiPublicHooksVerificationRemindersRoute
  '/api/public/hooks/violation-reminders': typeof ApiPublicHooksViolationRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inspections': typeof InspectionsRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-rentals': typeof MyRentalsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pending-agreements': typeof PendingAgreementsRoute
  '/pnl': typeof PnlRoute
  '/profile': typeof ProfileRoute
  '/refund-approvals': typeof RefundApprovalsRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/rentals': typeof RentalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/sms-log': typeof SmsLogRoute
  '/vendors': typeof VendorsRoute
  '/violations': typeof ViolationsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/create-task': typeof AdminCreateTaskRoute
  '/admin/extensions': typeof AdminExtensionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/breakeven': typeof AnalyticsBreakevenRoute
  '/analytics/costs': typeof AnalyticsCostsRoute
  '/analytics/failures': typeof AnalyticsFailuresRoute
  '/analytics/profitability': typeof AnalyticsProfitabilityRoute
  '/analytics/utilization': typeof AnalyticsUtilizationRoute
  '/auto-extend/$token': typeof AutoExtendTokenRoute
  '/extend/$token': typeof ExtendTokenRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/mechanic-job/$token': typeof MechanicJobTokenRoute
  '/my-rentals/$rentalId': typeof MyRentalsRentalIdRoute
  '/portal-signup/$rentalId': typeof PortalSignupRentalIdRoute
  '/rent/$token': typeof RentTokenRoute
  '/rent/paid': typeof RentPaidRoute
  '/rm-card/$token': typeof RmCardTokenRoute
  '/runner-task/$token': typeof RunnerTaskTokenRoute
  '/setup/$token': typeof SetupTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/verify-card/$token': typeof VerifyCardTokenRoute
  '/verify-payment/$rentalId': typeof VerifyPaymentRentalIdRoute
  '/violation/$token': typeof ViolationTokenRoute
  '/violations/bulk-upload': typeof ViolationsBulkUploadRoute
  '/violations/disputes': typeof ViolationsDisputesRoute
  '/work-order/$token': typeof WorkOrderTokenRoute
  '/api/public/cardholder-refuse': typeof ApiPublicCardholderRefuseRoute
  '/inspect/$vehicleId/$token': typeof InspectVehicleIdTokenRoute
  '/rent/portal/$rentalId': typeof RentPortalRentalIdRoute
  '/violation/$token/affidavit': typeof ViolationTokenAffidavitRoute
  '/api/public/hooks/auto-extension-links': typeof ApiPublicHooksAutoExtensionLinksRoute
  '/api/public/hooks/daily-reports': typeof ApiPublicHooksDailyReportsRoute
  '/api/public/hooks/monthly-backup': typeof ApiPublicHooksMonthlyBackupRoute
  '/api/public/hooks/repair-digest': typeof ApiPublicHooksRepairDigestRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/verification-reminders': typeof ApiPublicHooksVerificationRemindersRoute
  '/api/public/hooks/violation-reminders': typeof ApiPublicHooksViolationRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fleet': typeof FleetRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inspections': typeof InspectionsRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-rentals': typeof MyRentalsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/payroll-return': typeof PayrollReturnRoute
  '/pending-agreements': typeof PendingAgreementsRoute
  '/pnl': typeof PnlRoute
  '/profile': typeof ProfileRoute
  '/refund-approvals': typeof RefundApprovalsRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/rentals': typeof RentalsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runner-reports': typeof RunnerReportsRoute
  '/sms-log': typeof SmsLogRoute
  '/vendors': typeof VendorsRoute
  '/violations': typeof ViolationsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/create-task': typeof AdminCreateTaskRoute
  '/admin/extensions': typeof AdminExtensionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/breakeven': typeof AnalyticsBreakevenRoute
  '/analytics/costs': typeof AnalyticsCostsRoute
  '/analytics/failures': typeof AnalyticsFailuresRoute
  '/analytics/profitability': typeof AnalyticsProfitabilityRoute
  '/analytics/utilization': typeof AnalyticsUtilizationRoute
  '/auto-extend/$token': typeof AutoExtendTokenRoute
  '/extend/$token': typeof ExtendTokenRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/mechanic-job/$token': typeof MechanicJobTokenRoute
  '/my-rentals/$rentalId': typeof MyRentalsRentalIdRoute
  '/portal-signup/$rentalId': typeof PortalSignupRentalIdRoute
  '/rent/$token': typeof RentTokenRoute
  '/rent/paid': typeof RentPaidRoute
  '/rm-card/$token': typeof RmCardTokenRoute
  '/runner-task/$token': typeof RunnerTaskTokenRoute
  '/setup/$token': typeof SetupTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/verify-card/$token': typeof VerifyCardTokenRoute
  '/verify-payment/$rentalId': typeof VerifyPaymentRentalIdRoute
  '/violation/$token': typeof ViolationTokenRoute
  '/violations_/bulk-upload': typeof ViolationsBulkUploadRoute
  '/violations_/disputes': typeof ViolationsDisputesRoute
  '/work-order/$token': typeof WorkOrderTokenRoute
  '/api/public/cardholder-refuse': typeof ApiPublicCardholderRefuseRoute
  '/inspect/$vehicleId/$token': typeof InspectVehicleIdTokenRoute
  '/rent/portal/$rentalId': typeof RentPortalRentalIdRoute
  '/violation/$token_/affidavit': typeof ViolationTokenAffidavitRoute
  '/api/public/hooks/auto-extension-links': typeof ApiPublicHooksAutoExtensionLinksRoute
  '/api/public/hooks/daily-reports': typeof ApiPublicHooksDailyReportsRoute
  '/api/public/hooks/monthly-backup': typeof ApiPublicHooksMonthlyBackupRoute
  '/api/public/hooks/repair-digest': typeof ApiPublicHooksRepairDigestRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/verification-reminders': typeof ApiPublicHooksVerificationRemindersRoute
  '/api/public/hooks/violation-reminders': typeof ApiPublicHooksViolationRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/checklist'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/forgot-password'
    | '/inspections'
    | '/insurance'
    | '/login'
    | '/maintenance'
    | '/my-rentals'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pending-agreements'
    | '/pnl'
    | '/profile'
    | '/refund-approvals'
    | '/rental-agreement'
    | '/rentals'
    | '/reset-password'
    | '/runner-reports'
    | '/sms-log'
    | '/vendors'
    | '/violations'
    | '/admin/backups'
    | '/admin/create-task'
    | '/admin/extensions'
    | '/admin/notifications'
    | '/admin/tasks'
    | '/admin/users'
    | '/analytics/breakeven'
    | '/analytics/costs'
    | '/analytics/failures'
    | '/analytics/profitability'
    | '/analytics/utilization'
    | '/auto-extend/$token'
    | '/extend/$token'
    | '/fleet/$vehicleId'
    | '/mechanic-job/$token'
    | '/my-rentals/$rentalId'
    | '/portal-signup/$rentalId'
    | '/rent/$token'
    | '/rent/paid'
    | '/rm-card/$token'
    | '/runner-task/$token'
    | '/setup/$token'
    | '/sign/$token'
    | '/verify-card/$token'
    | '/verify-payment/$rentalId'
    | '/violation/$token'
    | '/violations/bulk-upload'
    | '/violations/disputes'
    | '/work-order/$token'
    | '/api/public/cardholder-refuse'
    | '/inspect/$vehicleId/$token'
    | '/rent/portal/$rentalId'
    | '/violation/$token/affidavit'
    | '/api/public/hooks/auto-extension-links'
    | '/api/public/hooks/daily-reports'
    | '/api/public/hooks/monthly-backup'
    | '/api/public/hooks/repair-digest'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/verification-reminders'
    | '/api/public/hooks/violation-reminders'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/checklist'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/forgot-password'
    | '/inspections'
    | '/insurance'
    | '/login'
    | '/maintenance'
    | '/my-rentals'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pending-agreements'
    | '/pnl'
    | '/profile'
    | '/refund-approvals'
    | '/rental-agreement'
    | '/rentals'
    | '/reset-password'
    | '/runner-reports'
    | '/sms-log'
    | '/vendors'
    | '/violations'
    | '/admin/backups'
    | '/admin/create-task'
    | '/admin/extensions'
    | '/admin/notifications'
    | '/admin/tasks'
    | '/admin/users'
    | '/analytics/breakeven'
    | '/analytics/costs'
    | '/analytics/failures'
    | '/analytics/profitability'
    | '/analytics/utilization'
    | '/auto-extend/$token'
    | '/extend/$token'
    | '/fleet/$vehicleId'
    | '/mechanic-job/$token'
    | '/my-rentals/$rentalId'
    | '/portal-signup/$rentalId'
    | '/rent/$token'
    | '/rent/paid'
    | '/rm-card/$token'
    | '/runner-task/$token'
    | '/setup/$token'
    | '/sign/$token'
    | '/verify-card/$token'
    | '/verify-payment/$rentalId'
    | '/violation/$token'
    | '/violations/bulk-upload'
    | '/violations/disputes'
    | '/work-order/$token'
    | '/api/public/cardholder-refuse'
    | '/inspect/$vehicleId/$token'
    | '/rent/portal/$rentalId'
    | '/violation/$token/affidavit'
    | '/api/public/hooks/auto-extension-links'
    | '/api/public/hooks/daily-reports'
    | '/api/public/hooks/monthly-backup'
    | '/api/public/hooks/repair-digest'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/verification-reminders'
    | '/api/public/hooks/violation-reminders'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/checklist'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fleet'
    | '/forgot-password'
    | '/inspections'
    | '/insurance'
    | '/login'
    | '/maintenance'
    | '/my-rentals'
    | '/payments'
    | '/payroll'
    | '/payroll-return'
    | '/pending-agreements'
    | '/pnl'
    | '/profile'
    | '/refund-approvals'
    | '/rental-agreement'
    | '/rentals'
    | '/reset-password'
    | '/runner-reports'
    | '/sms-log'
    | '/vendors'
    | '/violations'
    | '/admin/backups'
    | '/admin/create-task'
    | '/admin/extensions'
    | '/admin/notifications'
    | '/admin/tasks'
    | '/admin/users'
    | '/analytics/breakeven'
    | '/analytics/costs'
    | '/analytics/failures'
    | '/analytics/profitability'
    | '/analytics/utilization'
    | '/auto-extend/$token'
    | '/extend/$token'
    | '/fleet/$vehicleId'
    | '/mechanic-job/$token'
    | '/my-rentals/$rentalId'
    | '/portal-signup/$rentalId'
    | '/rent/$token'
    | '/rent/paid'
    | '/rm-card/$token'
    | '/runner-task/$token'
    | '/setup/$token'
    | '/sign/$token'
    | '/verify-card/$token'
    | '/verify-payment/$rentalId'
    | '/violation/$token'
    | '/violations_/bulk-upload'
    | '/violations_/disputes'
    | '/work-order/$token'
    | '/api/public/cardholder-refuse'
    | '/inspect/$vehicleId/$token'
    | '/rent/portal/$rentalId'
    | '/violation/$token_/affidavit'
    | '/api/public/hooks/auto-extension-links'
    | '/api/public/hooks/daily-reports'
    | '/api/public/hooks/monthly-backup'
    | '/api/public/hooks/repair-digest'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/verification-reminders'
    | '/api/public/hooks/violation-reminders'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  ChecklistRoute: typeof ChecklistRoute
  DriverPortalRoute: typeof DriverPortalRoute
  DriversRoute: typeof DriversRoute
  ExpensesRoute: typeof ExpensesRoute
  FleetRoute: typeof FleetRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InspectionsRoute: typeof InspectionsRoute
  InsuranceRoute: typeof InsuranceRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MyRentalsRoute: typeof MyRentalsRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  PayrollRoute: typeof PayrollRoute
  PayrollReturnRoute: typeof PayrollReturnRoute
  PendingAgreementsRoute: typeof PendingAgreementsRoute
  PnlRoute: typeof PnlRoute
  ProfileRoute: typeof ProfileRoute
  RefundApprovalsRoute: typeof RefundApprovalsRoute
  RentalAgreementRoute: typeof RentalAgreementRoute
  RentalsRoute: typeof RentalsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RunnerReportsRoute: typeof RunnerReportsRoute
  SmsLogRoute: typeof SmsLogRoute
  VendorsRoute: typeof VendorsRoute
  ViolationsRoute: typeof ViolationsRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminCreateTaskRoute: typeof AdminCreateTaskRoute
  AdminExtensionsRoute: typeof AdminExtensionsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AutoExtendTokenRoute: typeof AutoExtendTokenRoute
  ExtendTokenRoute: typeof ExtendTokenRoute
  MechanicJobTokenRoute: typeof MechanicJobTokenRoute
  PortalSignupRentalIdRoute: typeof PortalSignupRentalIdRoute
  RentTokenRoute: typeof RentTokenRoute
  RentPaidRoute: typeof RentPaidRoute
  RmCardTokenRoute: typeof RmCardTokenRoute
  RunnerTaskTokenRoute: typeof RunnerTaskTokenRoute
  SetupTokenRoute: typeof SetupTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  VerifyCardTokenRoute: typeof VerifyCardTokenRoute
  VerifyPaymentRentalIdRoute: typeof VerifyPaymentRentalIdRoute
  ViolationTokenRoute: typeof ViolationTokenRoute
  ViolationsBulkUploadRoute: typeof ViolationsBulkUploadRoute
  ViolationsDisputesRoute: typeof ViolationsDisputesRoute
  WorkOrderTokenRoute: typeof WorkOrderTokenRoute
  ApiPublicCardholderRefuseRoute: typeof ApiPublicCardholderRefuseRoute
  InspectVehicleIdTokenRoute: typeof InspectVehicleIdTokenRoute
  RentPortalRentalIdRoute: typeof RentPortalRentalIdRoute
  ViolationTokenAffidavitRoute: typeof ViolationTokenAffidavitRoute
  ApiPublicHooksAutoExtensionLinksRoute: typeof ApiPublicHooksAutoExtensionLinksRoute
  ApiPublicHooksDailyReportsRoute: typeof ApiPublicHooksDailyReportsRoute
  ApiPublicHooksMonthlyBackupRoute: typeof ApiPublicHooksMonthlyBackupRoute
  ApiPublicHooksRepairDigestRoute: typeof ApiPublicHooksRepairDigestRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  ApiPublicHooksVerificationRemindersRoute: typeof ApiPublicHooksVerificationRemindersRoute
  ApiPublicHooksViolationRemindersRoute: typeof ApiPublicHooksViolationRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-log': {
      id: '/sms-log'
      path: '/sms-log'
      fullPath: '/sms-log'
      preLoaderRoute: typeof SmsLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner-reports': {
      id: '/runner-reports'
      path: '/runner-reports'
      fullPath: '/runner-reports'
      preLoaderRoute: typeof RunnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-agreement': {
      id: '/rental-agreement'
      path: '/rental-agreement'
      fullPath: '/rental-agreement'
      preLoaderRoute: typeof RentalAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-approvals': {
      id: '/refund-approvals'
      path: '/refund-approvals'
      fullPath: '/refund-approvals'
      preLoaderRoute: typeof RefundApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-agreements': {
      id: '/pending-agreements'
      path: '/pending-agreements'
      fullPath: '/pending-agreements'
      preLoaderRoute: typeof PendingAgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-return': {
      id: '/payroll-return'
      path: '/payroll-return'
      fullPath: '/payroll-return'
      preLoaderRoute: typeof PayrollReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rentals': {
      id: '/my-rentals'
      path: '/my-rentals'
      fullPath: '/my-rentals'
      preLoaderRoute: typeof MyRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-portal': {
      id: '/driver-portal'
      path: '/driver-portal'
      fullPath: '/driver-portal'
      preLoaderRoute: typeof DriverPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-order/$token': {
      id: '/work-order/$token'
      path: '/work-order/$token'
      fullPath: '/work-order/$token'
      preLoaderRoute: typeof WorkOrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations_/disputes': {
      id: '/violations_/disputes'
      path: '/violations/disputes'
      fullPath: '/violations/disputes'
      preLoaderRoute: typeof ViolationsDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations_/bulk-upload': {
      id: '/violations_/bulk-upload'
      path: '/violations/bulk-upload'
      fullPath: '/violations/bulk-upload'
      preLoaderRoute: typeof ViolationsBulkUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violation/$token': {
      id: '/violation/$token'
      path: '/violation/$token'
      fullPath: '/violation/$token'
      preLoaderRoute: typeof ViolationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-payment/$rentalId': {
      id: '/verify-payment/$rentalId'
      path: '/verify-payment/$rentalId'
      fullPath: '/verify-payment/$rentalId'
      preLoaderRoute: typeof VerifyPaymentRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-card/$token': {
      id: '/verify-card/$token'
      path: '/verify-card/$token'
      fullPath: '/verify-card/$token'
      preLoaderRoute: typeof VerifyCardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$token': {
      id: '/setup/$token'
      path: '/setup/$token'
      fullPath: '/setup/$token'
      preLoaderRoute: typeof SetupTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner-task/$token': {
      id: '/runner-task/$token'
      path: '/runner-task/$token'
      fullPath: '/runner-task/$token'
      preLoaderRoute: typeof RunnerTaskTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rm-card/$token': {
      id: '/rm-card/$token'
      path: '/rm-card/$token'
      fullPath: '/rm-card/$token'
      preLoaderRoute: typeof RmCardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/paid': {
      id: '/rent/paid'
      path: '/rent/paid'
      fullPath: '/rent/paid'
      preLoaderRoute: typeof RentPaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$token': {
      id: '/rent/$token'
      path: '/rent/$token'
      fullPath: '/rent/$token'
      preLoaderRoute: typeof RentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-signup/$rentalId': {
      id: '/portal-signup/$rentalId'
      path: '/portal-signup/$rentalId'
      fullPath: '/portal-signup/$rentalId'
      preLoaderRoute: typeof PortalSignupRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rentals/$rentalId': {
      id: '/my-rentals/$rentalId'
      path: '/$rentalId'
      fullPath: '/my-rentals/$rentalId'
      preLoaderRoute: typeof MyRentalsRentalIdRouteImport
      parentRoute: typeof MyRentalsRoute
    }
    '/mechanic-job/$token': {
      id: '/mechanic-job/$token'
      path: '/mechanic-job/$token'
      fullPath: '/mechanic-job/$token'
      preLoaderRoute: typeof MechanicJobTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$vehicleId': {
      id: '/fleet/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/fleet/$vehicleId'
      preLoaderRoute: typeof FleetVehicleIdRouteImport
      parentRoute: typeof FleetRoute
    }
    '/extend/$token': {
      id: '/extend/$token'
      path: '/extend/$token'
      fullPath: '/extend/$token'
      preLoaderRoute: typeof ExtendTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-extend/$token': {
      id: '/auto-extend/$token'
      path: '/auto-extend/$token'
      fullPath: '/auto-extend/$token'
      preLoaderRoute: typeof AutoExtendTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/utilization': {
      id: '/analytics/utilization'
      path: '/utilization'
      fullPath: '/analytics/utilization'
      preLoaderRoute: typeof AnalyticsUtilizationRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/profitability': {
      id: '/analytics/profitability'
      path: '/profitability'
      fullPath: '/analytics/profitability'
      preLoaderRoute: typeof AnalyticsProfitabilityRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/failures': {
      id: '/analytics/failures'
      path: '/failures'
      fullPath: '/analytics/failures'
      preLoaderRoute: typeof AnalyticsFailuresRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/costs': {
      id: '/analytics/costs'
      path: '/costs'
      fullPath: '/analytics/costs'
      preLoaderRoute: typeof AnalyticsCostsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/breakeven': {
      id: '/analytics/breakeven'
      path: '/breakeven'
      fullPath: '/analytics/breakeven'
      preLoaderRoute: typeof AnalyticsBreakevenRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/extensions': {
      id: '/admin/extensions'
      path: '/admin/extensions'
      fullPath: '/admin/extensions'
      preLoaderRoute: typeof AdminExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-task': {
      id: '/admin/create-task'
      path: '/admin/create-task'
      fullPath: '/admin/create-task'
      preLoaderRoute: typeof AdminCreateTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violation/$token_/affidavit': {
      id: '/violation/$token_/affidavit'
      path: '/violation/$token/affidavit'
      fullPath: '/violation/$token/affidavit'
      preLoaderRoute: typeof ViolationTokenAffidavitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/portal/$rentalId': {
      id: '/rent/portal/$rentalId'
      path: '/rent/portal/$rentalId'
      fullPath: '/rent/portal/$rentalId'
      preLoaderRoute: typeof RentPortalRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$vehicleId/$token': {
      id: '/inspect/$vehicleId/$token'
      path: '/inspect/$vehicleId/$token'
      fullPath: '/inspect/$vehicleId/$token'
      preLoaderRoute: typeof InspectVehicleIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cardholder-refuse': {
      id: '/api/public/cardholder-refuse'
      path: '/api/public/cardholder-refuse'
      fullPath: '/api/public/cardholder-refuse'
      preLoaderRoute: typeof ApiPublicCardholderRefuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/violation-reminders': {
      id: '/api/public/hooks/violation-reminders'
      path: '/api/public/hooks/violation-reminders'
      fullPath: '/api/public/hooks/violation-reminders'
      preLoaderRoute: typeof ApiPublicHooksViolationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verification-reminders': {
      id: '/api/public/hooks/verification-reminders'
      path: '/api/public/hooks/verification-reminders'
      fullPath: '/api/public/hooks/verification-reminders'
      preLoaderRoute: typeof ApiPublicHooksVerificationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/repair-digest': {
      id: '/api/public/hooks/repair-digest'
      path: '/api/public/hooks/repair-digest'
      fullPath: '/api/public/hooks/repair-digest'
      preLoaderRoute: typeof ApiPublicHooksRepairDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monthly-backup': {
      id: '/api/public/hooks/monthly-backup'
      path: '/api/public/hooks/monthly-backup'
      fullPath: '/api/public/hooks/monthly-backup'
      preLoaderRoute: typeof ApiPublicHooksMonthlyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-reports': {
      id: '/api/public/hooks/daily-reports'
      path: '/api/public/hooks/daily-reports'
      fullPath: '/api/public/hooks/daily-reports'
      preLoaderRoute: typeof ApiPublicHooksDailyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-extension-links': {
      id: '/api/public/hooks/auto-extension-links'
      path: '/api/public/hooks/auto-extension-links'
      fullPath: '/api/public/hooks/auto-extension-links'
      preLoaderRoute: typeof ApiPublicHooksAutoExtensionLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsBreakevenRoute: typeof AnalyticsBreakevenRoute
  AnalyticsCostsRoute: typeof AnalyticsCostsRoute
  AnalyticsFailuresRoute: typeof AnalyticsFailuresRoute
  AnalyticsProfitabilityRoute: typeof AnalyticsProfitabilityRoute
  AnalyticsUtilizationRoute: typeof AnalyticsUtilizationRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsBreakevenRoute: AnalyticsBreakevenRoute,
  AnalyticsCostsRoute: AnalyticsCostsRoute,
  AnalyticsFailuresRoute: AnalyticsFailuresRoute,
  AnalyticsProfitabilityRoute: AnalyticsProfitabilityRoute,
  AnalyticsUtilizationRoute: AnalyticsUtilizationRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface FleetRouteChildren {
  FleetVehicleIdRoute: typeof FleetVehicleIdRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetVehicleIdRoute: FleetVehicleIdRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

interface MyRentalsRouteChildren {
  MyRentalsRentalIdRoute: typeof MyRentalsRentalIdRoute
}

const MyRentalsRouteChildren: MyRentalsRouteChildren = {
  MyRentalsRentalIdRoute: MyRentalsRentalIdRoute,
}

const MyRentalsRouteWithChildren = MyRentalsRoute._addFileChildren(
  MyRentalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  ChecklistRoute: ChecklistRoute,
  DriverPortalRoute: DriverPortalRoute,
  DriversRoute: DriversRoute,
  ExpensesRoute: ExpensesRoute,
  FleetRoute: FleetRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InspectionsRoute: InspectionsRoute,
  InsuranceRoute: InsuranceRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  MyRentalsRoute: MyRentalsRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  PayrollRoute: PayrollRoute,
  PayrollReturnRoute: PayrollReturnRoute,
  PendingAgreementsRoute: PendingAgreementsRoute,
  PnlRoute: PnlRoute,
  ProfileRoute: ProfileRoute,
  RefundApprovalsRoute: RefundApprovalsRoute,
  RentalAgreementRoute: RentalAgreementRoute,
  RentalsRoute: RentalsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RunnerReportsRoute: RunnerReportsRoute,
  SmsLogRoute: SmsLogRoute,
  VendorsRoute: VendorsRoute,
  ViolationsRoute: ViolationsRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminCreateTaskRoute: AdminCreateTaskRoute,
  AdminExtensionsRoute: AdminExtensionsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AutoExtendTokenRoute: AutoExtendTokenRoute,
  ExtendTokenRoute: ExtendTokenRoute,
  MechanicJobTokenRoute: MechanicJobTokenRoute,
  PortalSignupRentalIdRoute: PortalSignupRentalIdRoute,
  RentTokenRoute: RentTokenRoute,
  RentPaidRoute: RentPaidRoute,
  RmCardTokenRoute: RmCardTokenRoute,
  RunnerTaskTokenRoute: RunnerTaskTokenRoute,
  SetupTokenRoute: SetupTokenRoute,
  SignTokenRoute: SignTokenRoute,
  VerifyCardTokenRoute: VerifyCardTokenRoute,
  VerifyPaymentRentalIdRoute: VerifyPaymentRentalIdRoute,
  ViolationTokenRoute: ViolationTokenRoute,
  ViolationsBulkUploadRoute: ViolationsBulkUploadRoute,
  ViolationsDisputesRoute: ViolationsDisputesRoute,
  WorkOrderTokenRoute: WorkOrderTokenRoute,
  ApiPublicCardholderRefuseRoute: ApiPublicCardholderRefuseRoute,
  InspectVehicleIdTokenRoute: InspectVehicleIdTokenRoute,
  RentPortalRentalIdRoute: RentPortalRentalIdRoute,
  ViolationTokenAffidavitRoute: ViolationTokenAffidavitRoute,
  ApiPublicHooksAutoExtensionLinksRoute: ApiPublicHooksAutoExtensionLinksRoute,
  ApiPublicHooksDailyReportsRoute: ApiPublicHooksDailyReportsRoute,
  ApiPublicHooksMonthlyBackupRoute: ApiPublicHooksMonthlyBackupRoute,
  ApiPublicHooksRepairDigestRoute: ApiPublicHooksRepairDigestRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  ApiPublicHooksVerificationRemindersRoute:
    ApiPublicHooksVerificationRemindersRoute,
  ApiPublicHooksViolationRemindersRoute: ApiPublicHooksViolationRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
